-- Nova Chat — Supabase Schema
-- Run this SQL in your Supabase project SQL editor (Dashboard → SQL Editor → New query)
-- After running, set NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY
-- as environment variables in your Cloudflare Pages project settings.

-- ============ ENUMS ============
create type artifact_type as enum (
  'markdown', 'text', 'code', 'html', 'json', 'csv', 'yaml', 'xml', 'svg',
  'mermaid', 'image', 'pdf', 'document', 'spreadsheet', 'presentation'
);

create type message_role as enum ('user', 'assistant', 'system', 'tool');

create type message_status as enum ('streaming', 'complete', 'error', 'stopped');

create type tool_run_status as enum ('pending', 'approved', 'rejected', 'running', 'complete', 'error');

-- ============ USER PROFILES ============
create table if not exists user_profiles (
  id uuid primary key default gen_random_uuid(),
  email text unique,
  display_name text,
  avatar_url text,
  preferences jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============ CHATS ============
create table if not exists chats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references user_profiles(id) on delete cascade,
  title text not null default 'New chat',
  model text not null default 'glm-4.6',
  system_prompt text,
  temperature real default 0.7,
  max_tokens integer default 4096,
  tools_enabled boolean default true,
  pinned boolean default false,
  archived boolean default false,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_chats_user_id on chats(user_id);
create index if not exists idx_chats_updated on chats(updated_at desc);

-- ============ MESSAGES ============
create table if not exists messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references chats(id) on delete cascade,
  role message_role not null,
  content text not null default '',
  status message_status default 'complete',
  model text,
  tool_name text,
  tool_input jsonb,
  tool_output text,
  tokens_in integer,
  tokens_out integer,
  finish_reason text,
  metadata jsonb default '{}'::jsonb,
  artifact_ids uuid[] default '{}',
  created_at timestamptz not null default now()
);
create index if not exists idx_messages_chat_id on messages(chat_id);
create index if not exists idx_messages_created on messages(chat_id, created_at);

-- ============ ARTIFACTS ============
-- These are the real, downloadable files generated by Nova (like Claude.ai artifacts)
create table if not exists artifacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references user_profiles(id) on delete cascade,
  chat_id uuid references chats(id) on delete cascade,
  message_id uuid references messages(id) on delete set null,
  title text not null,
  type artifact_type not null,
  language text,
  content text not null default '',
  storage_key text,
  mime_type text,
  bytes integer,
  version integer default 1,
  parent_id uuid references artifacts(id) on delete set null,
  tags text[] default '{}',
  is_public boolean default false,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_artifacts_user on artifacts(user_id);
create index if not exists idx_artifacts_chat on artifacts(chat_id);
create index if not exists idx_artifacts_type on artifacts(type);

-- ============ SETTINGS ============
-- Per-user persistent settings (no localStorage!)
create table if not exists user_settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references user_profiles(id) on delete cascade,
  theme text not null default 'dark',
  font_sans text not null default 'inter',
  font_mono text not null default 'jetbrains-mono',
  font_display text not null default 'space-grotesk',
  density text not null default 'comfortable',
  accent_color text,
  reduce_motion boolean default false,
  send_on_enter boolean default true,
  show_thinking boolean default true,
  show_token_count boolean default false,
  streaming_enabled boolean default true,
  default_model text default 'glm-4.6',
  default_temperature real default 0.7,
  default_max_tokens integer default 4096,
  api_keys jsonb default '{}'::jsonb,
  custom_system_prompts jsonb default '[]'::jsonb,
  tool_permissions jsonb default '{}'::jsonb,
  shortcuts jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============ TOOL RUNS ============
create table if not exists tool_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references user_profiles(id) on delete cascade,
  chat_id uuid references chats(id) on delete set null,
  message_id uuid references messages(id) on delete set null,
  tool_name text not null,
  tool_input jsonb not null default '{}'::jsonb,
  tool_output jsonb,
  status tool_run_status default 'pending',
  risk_level text default 'safe',
  approved_by uuid references user_profiles(id),
  approved_at timestamptz,
  duration_ms integer,
  error text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_tool_runs_user on tool_runs(user_id);
create index if not exists idx_tool_runs_chat on tool_runs(chat_id);

-- ============ MEMORY ============
create table if not exists memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references user_profiles(id) on delete cascade,
  chat_id uuid references chats(id) on delete set null,
  content text not null,
  source text,
  tags text[] default '{}',
  importance real default 0.5,
  embedding vector(1536),
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_memories_user on memories(user_id);
create index if not exists idx_memories_embedding on memories using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- ============ FILE UPLOADS ============
create table if not exists file_uploads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references user_profiles(id) on delete cascade,
  chat_id uuid references chats(id) on delete set null,
  storage_key text not null,
  original_name text not null,
  mime_type text,
  bytes integer,
  text_content text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_file_uploads_user on file_uploads(user_id);

-- ============ EXTENSIONS ============
create extension if not exists "pgcrypto";
create extension if not exists "vector" with schema "extensions";

-- ============ ROW LEVEL SECURITY ============
alter table user_profiles enable row level security;
alter table chats enable row level security;
alter table messages enable row level security;
alter table artifacts enable row level security;
alter table user_settings enable row level security;
alter table tool_runs enable row level security;
alter table memories enable row level security;
alter table file_uploads enable row level security;

create policy "all_users_profiles" on user_profiles for all using (true) with check (true);
create policy "all_chats" on chats for all using (true) with check (true);
create policy "all_messages" on messages for all using (true) with check (true);
create policy "all_artifacts" on artifacts for all using (true) with check (true);
create policy "all_settings" on user_settings for all using (true) with check (true);
create policy "all_tool_runs" on tool_runs for all using (true) with check (true);
create policy "all_memories" on memories for all using (true) with check (true);
create policy "all_file_uploads" on file_uploads for all using (true) with check (true);

-- ============ TRIGGERS ============
create or replace function touch_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_chats_touch on chats;
create trigger trg_chats_touch before update on chats for each row execute function touch_updated_at();

drop trigger if exists trg_messages_touch on messages;
create trigger trg_messages_touch before update on messages for each row execute function touch_updated_at();

drop trigger if exists trg_artifacts_touch on artifacts;
create trigger trg_artifacts_touch before update on artifacts for each row execute function touch_updated_at();

drop trigger if exists trg_settings_touch on user_settings;
create trigger trg_settings_touch before update on user_settings for each row execute function touch_updated_at();

-- ============ HELPER: get_or_create_default_user ============
create or replace function get_or_create_default_user() returns uuid as $$
declare
  uid uuid;
begin
  select id into uid from user_profiles where email = 'default@nova-chat.local' limit 1;
  if uid is null then
    insert into user_profiles (email, display_name)
    values ('default@nova-chat.local', 'Default User')
    returning id into uid;
    insert into user_settings (user_id) values (uid);
  end if;
  return uid;
end;
$$ language plpgsql;
