import { appendAudit, getServerSnapshot, loadBackendStore, recordUsage } from '../backend/repository';
import { createWebhookSignature } from '../backend/security';
import { NovaFile } from '../storage/workspace';
import type { AgentEvent, RiskLevel, ToolContext, ToolDefinition } from './runtime';

export type AdvancedToolId = 'redact-sensitive' | 'transform-json' | 'workspace-manifest' | 'project-health' | 'workflow-plan' | 'verify-webhook' | 'package-export' | 'diagnostic-report';
const jsonInput = (input: string) => { try { return JSON.parse(input) as Record<string, unknown>; } catch { throw new Error('Tool input must be valid JSON.'); } };
const emit = async (context: ToolContext, type: AgentEvent['type'], message: string, metadata?: Record<string, unknown>) => context.log({ type, message, metadata });

export const advancedTools: ToolDefinition[] = [
  { id: 'redact-sensitive', name: 'Sensitive data redactor', description: 'Remove secrets, tokens, emails, and credential-shaped values from text before sharing.', risk: 'safe', input: 'text', run: async (input, context) => { const output = input.replace(/([A-Za-z0-9._%+-]+)@([A-Za-z0-9.-]+\.[A-Za-z]{2,})/g, '[email redacted]').replace(/(Bearer\s+)[A-Za-z0-9._-]+/gi, '$1[redacted]').replace(/(api[_-]?key|token|secret|password)\s*[:=]\s*[^\s,;]+/gi, '$1=[redacted]'); await emit(context, 'run.completed', 'Sensitive values were redacted locally.'); return output; } },
  { id: 'transform-json', name: 'JSON transformer', description: 'Select, flatten, and normalize structured JSON records for downstream tools.', risk: 'safe', input: 'json', run: async (input) => { const value = jsonInput(input); const fields = Array.isArray(value.fields) ? value.fields.map(String) : Object.keys(value).filter((key) => key !== 'fields'); const source = Array.isArray(value.records) ? value.records : [value]; return JSON.stringify(source.map((record) => Object.fromEntries(fields.filter((field) => field in (record as Record<string, unknown>)).map((field) => [field, (record as Record<string, unknown>)[field]]))), null, 2); } },
  { id: 'workspace-manifest', name: 'Workspace manifest', description: 'Build a deterministic file and media manifest with counts, types, and total size.', risk: 'safe', input: 'file', run: async (_input, context) => { const counts = context.files.reduce<Record<string, number>>((acc, file) => { acc[file.kind] = (acc[file.kind] ?? 0) + 1; return acc; }, {}); const result = { generatedAt: new Date().toISOString(), totalFiles: context.files.length, totalBytes: context.files.reduce((sum, file) => sum + file.size, 0), byKind: counts, files: context.files.map((file) => ({ id: file.id, name: file.name, kind: file.kind, size: file.size, updatedAt: file.updatedAt })) }; return JSON.stringify(result, null, 2); } },
  { id: 'project-health', name: 'Project health analyzer', description: 'Summarize blocked, overdue, unassigned, and completed task risk across the workspace.', risk: 'review', input: 'json', run: async (_input, context) => { const store = await loadBackendStore(); const now = Date.now(); const overdue = store.tasks.filter((task) => task.dueAt && new Date(task.dueAt).getTime() < now && task.status !== 'done').length; const result = { projects: store.projects.length, tasks: store.tasks.length, blocked: store.tasks.filter((task) => task.status === 'blocked').length, overdue, unassigned: store.tasks.filter((task) => !task.assigneeId && task.status !== 'done').length, completed: store.tasks.filter((task) => task.status === 'done').length, connectors: store.connectors }; await appendAudit({ workspaceId: 'nova-local', actorId: 'local-agent', action: 'tool.project-health', resource: 'workspace', risk: 'low', metadata: result }); await emit(context, 'run.completed', 'Project health report generated.'); return JSON.stringify(result, null, 2); } },
  { id: 'workflow-plan', name: 'Workflow planner', description: 'Turn a goal into a typed, approval-aware execution plan.', risk: 'review', input: 'text', run: async (input) => JSON.stringify({ goal: input.trim(), plan: [{ step: 1, action: 'Inspect local context', risk: 'safe' }, { step: 2, action: 'Prepare structured changes', risk: 'safe' }, { step: 3, action: 'Request approval for external effects', risk: 'review' }, { step: 4, action: 'Execute and record audit trail', risk: 'sensitive' }], requiresApproval: true, generatedAt: new Date().toISOString() }, null, 2) },
  { id: 'verify-webhook', name: 'Webhook verifier', description: 'Verify an inbound webhook signature before processing its event payload.', risk: 'sensitive', input: 'json', run: async (input) => { const value = jsonInput(input); const payload = String(value.payload ?? ''); const secret = String(value.secret ?? ''); const expected = createWebhookSignature(payload, secret); return JSON.stringify({ valid: expected === String(value.signature ?? ''), expectedPrefix: expected.slice(0, 12), eventType: value.eventType ?? 'unknown' }, null, 2); } },
  { id: 'package-export', name: 'Export package planner', description: 'Prepare an export plan with selected files, checksum placeholders, and approval requirements.', risk: 'sensitive', input: 'json', run: async (input, context) => { const value = jsonInput(input); const selected = Array.isArray(value.fileIds) ? new Set(value.fileIds.map(String)) : null; const files = context.files.filter((file) => !selected || selected.has(file.id)); return JSON.stringify({ packageId: `export-${Date.now()}`, requiresApproval: true, files: files.map((file) => ({ id: file.id, name: file.name, size: file.size, checksum: 'pending-local-checksum' })), totalBytes: files.reduce((sum, file) => sum + file.size, 0) }, null, 2); } },
  { id: 'diagnostic-report', name: 'Diagnostic report', description: 'Generate a local health report across backend data, files, agent events, and remote readiness.', risk: 'safe', input: 'json', run: async (_input, context) => { const store = await loadBackendStore(); const snapshot = await getServerSnapshot('nova-local'); await recordUsage({ workspaceId: 'nova-local', day: new Date().toISOString().slice(0, 10), runs: 1, toolCalls: 1, filesIndexed: context.files.length, syncs: 0, errors: 0, latencyMs: 0 }); return JSON.stringify({ generatedAt: new Date().toISOString(), backend: { projects: store.projects.length, tasks: store.tasks.length, workflows: store.workflows.length, connectors: store.connectors.length }, workspace: { files: context.files.length, bytes: context.files.reduce((sum, file) => sum + file.size, 0) }, snapshotCursor: snapshot.cursor, status: 'healthy' }, null, 2); } }
];

