import { checkConnectors } from '../backend/services';
import { createSchedule, loadAutomationRuns, loadSchedules, loadWebhookSubscriptions, replayEvent, runSchedule } from '../backend/automation';
import { loadBackendStore } from '../backend/repository';
import type { BackendEvent } from '../backend/contracts';
import type { AgentEvent, ToolContext, ToolDefinition } from './runtime';
const objectInput = (input: string) => { try { return JSON.parse(input) as Record<string, unknown>; } catch { throw new Error('Expected a valid JSON object.'); } };
const log = async (context: ToolContext, message: string) => context.log({ type: 'run.completed' as AgentEvent['type'], message });
export const operationsTools: ToolDefinition[] = [
  { id: 'schedule-automation', name: 'Automation scheduler', description: 'Create or run a durable local schedule for a backend tool.', risk: 'review', input: 'json', run: async (input, context) => { const value = objectInput(input); const action = String(value.action ?? 'create'); if (action === 'run') { const schedule = (await loadSchedules()).find((item) => item.id === String(value.scheduleId)); if (!schedule) throw new Error('Schedule not found.'); const result = await runSchedule(schedule); await log(context, `Schedule ${schedule.name} completed.`); return JSON.stringify(result, null, 2); } const schedule = await createSchedule({ workspaceId: String(value.workspaceId ?? 'nova-local'), name: String(value.name ?? 'Nova automation'), toolId: String(value.toolId ?? 'diagnostic-report'), input: (value.input as Record<string, unknown>) ?? {}, cadence: (value.cadence as 'hourly' | 'daily' | 'weekly' | 'manual') ?? 'daily' }); return JSON.stringify(schedule, null, 2); } },
  { id: 'connector-audit', name: 'Connector auditor', description: 'Check configured connectors and produce a safe operational status report.', risk: 'safe', input: 'json', run: async (_input, context) => { const result = await checkConnectors('nova-local'); await log(context, 'Connector audit completed.'); return JSON.stringify(result, null, 2); } },
  { id: 'webhook-inventory', name: 'Webhook inventory', description: 'List inbound webhook routes, subscribed event types, and delivery counts.', risk: 'safe', input: 'json', run: async () => JSON.stringify(await loadWebhookSubscriptions(), null, 2) },
  { id: 'event-replay', name: 'Event replay operator', description: 'Replay a selected backend event with an audit record for controlled recovery.', risk: 'sensitive', input: 'json', run: async (input, context) => { const value = objectInput(input); const event = value.event as BackendEvent; if (!event?.id || !event.type) throw new Error('A typed event is required.'); const result = await replayEvent(event); await log(context, `Event ${event.id} replayed.`); return JSON.stringify(result, null, 2); } },
  { id: 'audit-report', name: 'Audit report builder', description: 'Summarize recent backend actions by risk, resource, and actor.', risk: 'safe', input: 'json', run: async () => { const store = await loadBackendStore(); const byRisk = store.audit.reduce<Record<string, number>>((acc, item) => { acc[item.risk] = (acc[item.risk] ?? 0) + 1; return acc; }, {}); const byResource = store.audit.reduce<Record<string, number>>((acc, item) => { acc[item.resource] = (acc[item.resource] ?? 0) + 1; return acc; }, {}); return JSON.stringify({ total: store.audit.length, byRisk, byResource, recent: store.audit.slice(0, 20) }, null, 2); } },
  { id: 'automation-report', name: 'Automation report', description: 'Summarize schedules, recent runs, and pending operational work.', risk: 'safe', input: 'json', run: async () => JSON.stringify({ schedules: await loadSchedules(), runs: (await loadAutomationRuns()).slice(0, 25) }, null, 2) }
];
