import { loadBackendConfig } from '../backend/client';
import { loadDeadLetters, processWorkerQueue } from '../backend/worker';
import { loadBackendStore, updateTask } from '../backend/repository';
import { getSecret } from '../backend/secureStorage';
import type { ToolContext, ToolDefinition } from './runtime';
const parse = (input: string) => { try { return JSON.parse(input) as Record<string, unknown>; } catch { throw new Error('Input must be valid JSON.'); } };
const safeUrl = (value: string) => { const url = new URL(value); if (url.protocol !== 'https:' && url.hostname !== 'localhost' && url.hostname !== '127.0.0.1') throw new Error('Only HTTPS or localhost URLs are allowed.'); return url; };
export const productionTools: ToolDefinition[] = [
  { id: 'http-connector-test', name: 'HTTP connector test', description: 'Perform a bounded, redacted health request against an approved HTTPS connector.', risk: 'review', input: 'json', run: async (input) => { const value = parse(input); const url = safeUrl(String(value.url ?? '')); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 8000); try { const response = await fetch(url.toString(), { method: 'GET', headers: { Accept: 'application/json' }, signal: controller.signal }); return JSON.stringify({ ok: response.ok, status: response.status, url: `${url.origin}${url.pathname}`, contentType: response.headers.get('content-type') }, null, 2); } finally { clearTimeout(timer); } } },
  { id: 'json-schema-check', name: 'JSON schema check', description: 'Validate required fields and primitive types before a record enters a workflow.', risk: 'safe', input: 'json', run: async (input) => { const value = parse(input); const record = (value.record ?? {}) as Record<string, unknown>; const required = Array.isArray(value.required) ? value.required.map(String) : []; const types = (value.types ?? {}) as Record<string, string>; const errors = required.filter((key) => !(key in record)).map((key) => `${key} is required`); for (const [key, type] of Object.entries(types)) if (key in record && typeof record[key] !== type) errors.push(`${key} must be ${type}`); return JSON.stringify({ valid: errors.length === 0, errors, checkedFields: Object.keys(record).length }, null, 2); } },
  { id: 'bulk-task-update', name: 'Bulk task updater', description: 'Apply a validated status change to a selected set of local tasks with audit-safe persistence.', risk: 'sensitive', input: 'json', run: async (input) => { const value = parse(input); const ids = Array.isArray(value.taskIds) ? value.taskIds.map(String) : []; const status = String(value.status) as 'backlog' | 'todo' | 'in_progress' | 'blocked' | 'done'; if (!['backlog','todo','in_progress','blocked','done'].includes(status)) throw new Error('Unsupported task status.'); const store = await loadBackendStore(); const selected = store.tasks.filter((task) => ids.includes(task.id)); for (const task of selected) await updateTask(task.id, { status }); return JSON.stringify({ updated: selected.length, status, taskIds: selected.map((task) => task.id) }, null, 2); } },
  { id: 'dead-letter-recovery', name: 'Dead-letter recovery', description: 'Inspect failed jobs and explicitly reprocess due work after operator review.', risk: 'sensitive', input: 'json', run: async (input) => { const value = parse(input); if (value.action !== 'process') return JSON.stringify({ deadLetters: await loadDeadLetters() }, null, 2); return JSON.stringify(await processWorkerQueue('nova-local', 'recovery-operator'), null, 2); } },
  { id: 'credential-readiness', name: 'Credential readiness', description: 'Check whether a backend credential is securely stored without revealing its value.', risk: 'safe', input: 'json', run: async () => { const config = await loadBackendConfig(); const token = await getSecret('backend-api-token'); return JSON.stringify({ remoteMode: config.mode === 'remote', endpointConfigured: Boolean(config.baseUrl), tokenStored: Boolean(token), transport: config.baseUrl.startsWith('https://') ? 'https' : 'local-or-offline' }, null, 2); } },
  { id: 'workspace-integrity', name: 'Workspace integrity check', description: 'Detect duplicate IDs, missing project references, and malformed task relationships.', risk: 'safe', input: 'json', run: async () => { const store = await loadBackendStore(); const projectIds = new Set(store.projects.map((project) => project.id)); const duplicateTasks = store.tasks.length - new Set(store.tasks.map((task) => task.id)).size; const orphanTasks = store.tasks.filter((task) => !projectIds.has(task.projectId)).map((task) => task.id); return JSON.stringify({ valid: duplicateTasks === 0 && orphanTasks.length === 0, duplicateTasks, orphanTasks, projects: store.projects.length, tasks: store.tasks.length }, null, 2); } }
];
