import AsyncStorage from '@react-native-async-storage/async-storage';
import type { NovaFile } from '../storage/workspace';

export type RiskLevel = 'safe' | 'review' | 'sensitive';
export type RunStatus = 'queued' | 'running' | 'waiting_approval' | 'completed' | 'failed' | 'cancelled';
export type JobStatus = 'queued' | 'running' | 'retrying' | 'completed' | 'failed';
export type AgentEvent = { id: string; runId?: string; type: 'run.created' | 'job.enqueued' | 'job.started' | 'job.retrying' | 'approval.requested' | 'approval.resolved' | 'file.imported' | 'file.exported' | 'run.completed' | 'run.failed'; message: string; createdAt: string; metadata?: Record<string, unknown> };
export type AgentJob = { id: string; runId: string; toolId: string; input: string; status: JobStatus; attempts: number; maxAttempts: number; nextAttemptAt?: string; createdAt: string; updatedAt: string; error?: string };
export type AgentRun = { id: string; title: string; input: string; status: RunStatus; steps: AgentStep[]; jobIds: string[]; createdAt: string; updatedAt: string; error?: string };
export type AgentStep = { id: string; name: string; status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped'; output?: string; startedAt?: string; completedAt?: string };
export type Approval = { id: string; runId: string; jobId?: string; title: string; detail: string; risk: RiskLevel; status: 'pending' | 'approved' | 'rejected'; createdAt: string; resolvedAt?: string };
export type Memory = { id: string; content: string; tags: string[]; source: string; createdAt: string; updatedAt: string };
export type ToolContext = { files: NovaFile[]; log: (event: Omit<AgentEvent, 'id' | 'createdAt'>) => Promise<void> };
export type ToolDefinition = { id: string; name: string; description: string; risk: RiskLevel; input: 'text' | 'file' | 'json'; run: (input: string, context: ToolContext) => Promise<string> };

const keys = { runs: 'nova.agent.runs.v2', approvals: 'nova.agent.approvals.v2', memories: 'nova.agent.memories.v2', jobs: 'nova.agent.jobs.v2', events: 'nova.agent.events.v2' } as const;
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
export type RuntimeData = { runs: AgentRun[]; approvals: Approval[]; memories: Memory[]; jobs: AgentJob[]; events: AgentEvent[] };
export async function loadRuntime(): Promise<RuntimeData> { const values = await Promise.all(Object.values(keys).map((key) => AsyncStorage.getItem(key))); return { runs: parse(values[0], []), approvals: parse(values[1], []), memories: parse(values[2], []), jobs: parse(values[3], []), events: parse(values[4], []) }; }
export async function saveRuntime(data: RuntimeData) { await AsyncStorage.multiSet(Object.entries(keys).map(([name, key]) => [key, JSON.stringify(data[name as keyof RuntimeData])] as [string, string])); }
export async function appendEvent(event: Omit<AgentEvent, 'id' | 'createdAt'>) { const data = await loadRuntime(); data.events = [{ ...event, id: `event-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, createdAt: new Date().toISOString() }, ...data.events].slice(0, 500); await AsyncStorage.setItem(keys.events, JSON.stringify(data.events)); return data.events[0]; }
export function createRun(input: string): AgentRun { const now = new Date().toISOString(); return { id: `run-${Date.now()}`, title: input.trim().slice(0, 42) || 'Untitled agent run', input: input.trim(), status: 'queued', jobIds: [], steps: [{ id: 'inspect', name: 'Inspect request', status: 'pending' }, { id: 'plan', name: 'Build execution plan', status: 'pending' }, { id: 'execute', name: 'Execute local tools', status: 'pending' }, { id: 'review', name: 'Review result', status: 'pending' }], createdAt: now, updatedAt: now }; }
export function createJob(runId: string, toolId: string, input: string): AgentJob { const now = new Date().toISOString(); return { id: `job-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, runId, toolId, input, status: 'queued', attempts: 0, maxAttempts: 3, createdAt: now, updatedAt: now }; }
export function requestApproval(run: AgentRun, job: AgentJob, risk: RiskLevel): Approval { return { id: `approval-${Date.now()}`, runId: run.id, jobId: job.id, title: 'Approval required', detail: `Nova is ready to run “${job.toolId}” for “${run.title}”.`, risk, status: 'pending', createdAt: new Date().toISOString() }; }
export function addMemory(content: string, tags: string[] = [], source = 'manual'): Memory { const now = new Date().toISOString(); return { id: `memory-${Date.now()}`, content: content.trim(), tags, source, createdAt: now, updatedAt: now }; }
export function searchMemories(memories: Memory[], query: string) { const terms = query.toLowerCase().split(/\s+/).filter(Boolean); return memories.filter((memory) => terms.every((term) => `${memory.content} ${memory.tags.join(' ')}`.toLowerCase().includes(term))); }
export async function clearRuntime() { await AsyncStorage.multiRemove(Object.values(keys)); }
export async function exportRuntime(data: RuntimeData) { return JSON.stringify({ version: 2, exportedAt: new Date().toISOString(), ...data }, null, 2); }
export async function importRuntime(json: string) { const value = JSON.parse(json) as Partial<RuntimeData>; const data: RuntimeData = { runs: Array.isArray(value.runs) ? value.runs : [], approvals: Array.isArray(value.approvals) ? value.approvals : [], memories: Array.isArray(value.memories) ? value.memories : [], jobs: Array.isArray(value.jobs) ? value.jobs : [], events: Array.isArray(value.events) ? value.events : [] }; await saveRuntime(data); return data; }

export const agentTools: ToolDefinition[] = [
  { id: 'extract', name: 'Signal extractor', description: 'Find decisions, risks, and next actions in notes.', risk: 'safe', input: 'text', run: async (input) => `Signals found\n\nDecision: ${input.trim() || 'No decision yet.'}\nRisk: Validate assumptions before committing.\nNext action: Choose one measurable follow-up.` },
  { id: 'json', name: 'Structured output', description: 'Turn free text into a predictable local record.', risk: 'safe', input: 'text', run: async (input) => JSON.stringify({ objective: input.trim() || 'Untitled objective', constraints: [], actions: [], confidence: 'medium' }, null, 2) },
  { id: 'file-index', name: 'File indexer', description: 'Create searchable metadata for the Nova workspace.', risk: 'safe', input: 'file', run: async (_input, context) => `${context.files.length} workspace files are indexed and ready for local search.` },
  { id: 'media-summary', name: 'Media summary', description: 'Prepare a local media manifest for review or export.', risk: 'review', input: 'file', run: async (_input, context) => JSON.stringify({ media: context.files.filter((file) => ['image', 'audio', 'video'].includes(file.kind)).map((file) => ({ name: file.name, kind: file.kind, size: file.size })) }, null, 2) },
  { id: 'export', name: 'Workspace export', description: 'Package local metadata for user-approved sharing.', risk: 'sensitive', input: 'json', run: async (_input, context) => `Prepared export manifest for ${context.files.length} files. Approval gate passed.` },
];
export const pipelines = [{ id: 'research', name: 'Research sprint', description: 'Plan, synthesize, and review a research question.', steps: ['Capture question', 'Decompose unknowns', 'Draft synthesis', 'Create next actions'] }, { id: 'project', name: 'Project kickoff', description: 'Turn an idea into a practical delivery plan.', steps: ['Define outcome', 'Map milestones', 'Identify risks', 'Set first action'] }, { id: 'media', name: 'Media review', description: 'Index, inspect, and export local media safely.', steps: ['Index media', 'Check permissions', 'Prepare manifest', 'Request export approval'] }];
export type Pipeline = typeof pipelines[number];
export async function runPipeline(pipeline: Pipeline, input: string) { const run = createRun(`${pipeline.name}: ${input}`); run.steps = pipeline.steps.map((name, index) => ({ id: `${run.id}-${index}`, name, status: index === 0 ? 'completed' : 'pending', output: index === 0 ? input : undefined })); run.status = run.steps.length === 1 ? 'completed' : 'running'; return run; }
