import AsyncStorage from '@react-native-async-storage/async-storage';

export type RunStatus = 'queued' | 'running' | 'waiting_approval' | 'completed' | 'failed' | 'cancelled';
export type AgentRun = { id: string; title: string; input: string; status: RunStatus; steps: AgentStep[]; createdAt: string; updatedAt: string; error?: string };
export type AgentStep = { id: string; name: string; status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped'; output?: string; startedAt?: string; completedAt?: string };
export type Approval = { id: string; runId: string; title: string; detail: string; status: 'pending' | 'approved' | 'rejected'; createdAt: string };
export type Memory = { id: string; content: string; tags: string[]; source: string; createdAt: string; updatedAt: string };

const keys = { runs: 'nova.agent.runs', approvals: 'nova.agent.approvals', memories: 'nova.agent.memories' } as const;
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
export async function loadRuntime() { const [runs, approvals, memories] = await Promise.all(Object.values(keys).map((key) => AsyncStorage.getItem(key))); return { runs: parse<AgentRun[]>(runs, []), approvals: parse<Approval[]>(approvals, []), memories: parse<Memory[]>(memories, []) }; }
export async function saveRuntime(data: Awaited<ReturnType<typeof loadRuntime>>) { const entries: [string, unknown][] = [[keys.runs, data.runs], [keys.approvals, data.approvals], [keys.memories, data.memories]]; await Promise.all(entries.map(([key, value]) => AsyncStorage.setItem(key, JSON.stringify(value)))); }
export function createRun(input: string): AgentRun { const now = new Date().toISOString(); return { id: `run-${Date.now()}`, title: input.trim().slice(0, 42) || 'Untitled agent run', input: input.trim(), status: 'queued', steps: [{ id: 'inspect', name: 'Inspect request', status: 'pending' }, { id: 'plan', name: 'Build execution plan', status: 'pending' }, { id: 'execute', name: 'Execute local tools', status: 'pending' }, { id: 'review', name: 'Review result', status: 'pending' }], createdAt: now, updatedAt: now }; }
export function advanceRun(run: AgentRun): AgentRun { const index = run.steps.findIndex((step) => step.status === 'pending'); if (index < 0) return { ...run, status: 'completed', updatedAt: new Date().toISOString() }; const steps = run.steps.map((step, i) => i === index ? { ...step, status: 'completed' as const, output: i === 0 ? `Request accepted: ${run.input}` : i === 1 ? 'Plan: clarify, execute, verify, and save the result.' : i === 2 ? 'Local tool execution completed without network access.' : 'Result reviewed and ready for you.' } : step); return { ...run, status: index === run.steps.length - 1 ? 'completed' : 'running', steps, updatedAt: new Date().toISOString() }; }
export function requestApproval(run: AgentRun): Approval { return { id: `approval-${Date.now()}`, runId: run.id, title: 'Approve local agent action', detail: `Nova wants to continue the run “${run.title}”.`, status: 'pending', createdAt: new Date().toISOString() }; }
export function addMemory(content: string, tags: string[] = [], source = 'manual'): Memory { const now = new Date().toISOString(); return { id: `memory-${Date.now()}`, content: content.trim(), tags, source, createdAt: now, updatedAt: now }; }
export function searchMemories(memories: Memory[], query: string) { const terms = query.toLowerCase().split(/\s+/).filter(Boolean); return memories.filter((memory) => terms.every((term) => `${memory.content} ${memory.tags.join(' ')}`.toLowerCase().includes(term))); }
export async function clearRuntime() { await Promise.all(Object.values(keys).map((key) => AsyncStorage.removeItem(key))); }
export async function exportRuntime(data: Awaited<ReturnType<typeof loadRuntime>>) { return JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), ...data }, null, 2); }
export async function importRuntime(json: string) { const value = JSON.parse(json) as Partial<Awaited<ReturnType<typeof loadRuntime>>>; const data = { runs: Array.isArray(value.runs) ? value.runs : [], approvals: Array.isArray(value.approvals) ? value.approvals : [], memories: Array.isArray(value.memories) ? value.memories : [] }; await saveRuntime(data); return data; }

export type Pipeline = { id: string; name: string; description: string; steps: string[] };
export const pipelines: Pipeline[] = [{ id: 'research', name: 'Research sprint', description: 'Plan, synthesize, and review a research question.', steps: ['Capture question', 'Decompose unknowns', 'Draft synthesis', 'Create next actions'] }, { id: 'project', name: 'Project kickoff', description: 'Turn an idea into a practical delivery plan.', steps: ['Define outcome', 'Map milestones', 'Identify risks', 'Set first action'] }, { id: 'memory', name: 'Memory maintenance', description: 'Review local memories and surface useful connections.', steps: ['Index memories', 'Find related notes', 'Suggest tags', 'Prepare review'] }];
export async function runPipeline(pipeline: Pipeline, input: string) { const run = createRun(`${pipeline.name}: ${input}`); run.steps = pipeline.steps.map((name, index) => ({ id: `${run.id}-${index}`, name, status: index === 0 ? 'completed' : 'pending', output: index === 0 ? input : undefined })); run.status = run.steps.length === 1 ? 'completed' : 'running'; return run; }

export type ToolDefinition = { id: string; name: string; description: string; risk: 'safe' | 'review'; run: (input: string) => string };
export const agentTools: ToolDefinition[] = [{ id: 'extract', name: 'Signal extractor', description: 'Find decisions, risks, and next actions in notes.', risk: 'safe', run: (input) => `Signals found\n\nDecision: ${input.trim() || 'No decision yet.'}\nRisk: Validate assumptions before committing.\nNext action: Choose one measurable follow-up.` }, { id: 'json', name: 'Structured output', description: 'Turn free text into a predictable local record.', risk: 'safe', run: (input) => JSON.stringify({ objective: input.trim() || 'Untitled objective', constraints: [], actions: [], confidence: 'medium' }, null, 2) }, { id: 'approval', name: 'Approval gate', description: 'Pause a run before a sensitive action.', risk: 'review', run: (input) => `Approval required before continuing: ${input.trim() || 'No action specified.'}` }];
