export type Rule = { indicator: string; operator: ">" | ">=" | "<" | "<=" | "=="; value: number | string };

export type Strategy = {
  id: string;
  name: string;
  description: string;
  entryRules: Rule[];
  exitRules: Rule[];
  logic: "AND" | "OR";
  direction: "BUY" | "SELL" | "AUTO";
  atrStopMultiple: number;
  takeProfitMultiple: number;
  riskPerTradePct: number;
  maxBarsInTrade: number;
};

export const STRATEGIES: Strategy[] = [
  {
    id: "rsi_reversal",
    name: "RSI Mean Reversion",
    description: "Buy oversold, sell overbought",
    entryRules: [{ indicator: "RSI_14", operator: "<", value: 30 }],
    exitRules: [{ indicator: "RSI_14", operator: ">", value: 70 }],
    logic: "AND",
    direction: "AUTO",
    atrStopMultiple: 1.5,
    takeProfitMultiple: 2,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
  {
    id: "macd_trend",
    name: "MACD Trend Following",
    description: "Follow MACD signal crossovers",
    entryRules: [{ indicator: "MACD", operator: ">", value: 0 }],
    exitRules: [{ indicator: "MACD", operator: "<", value: 0 }],
    logic: "AND",
    direction: "AUTO",
    atrStopMultiple: 2,
    takeProfitMultiple: 3,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
  {
    id: "adx_strength",
    name: "ADX Strength Entry",
    description: "Only trade strong trends",
    entryRules: [
      { indicator: "ADX_14", operator: ">", value: 25 },
      { indicator: "PLUS_DI", operator: ">", value: 20 },
    ],
    exitRules: [{ indicator: "ADX_14", operator: "<", value: 20 }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 2,
    takeProfitMultiple: 3,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
  {
    id: "bb_squeeze",
    name: "Bollinger Band Squeeze",
    description: "Trade breakout from low volatility",
    entryRules: [
      { indicator: "BB_PERCENT", operator: ">", value: 0.8 },
      { indicator: "VOLATILITY_20", operator: "<", value: 0.15 },
    ],
    exitRules: [{ indicator: "BB_PERCENT", operator: "<", value: 0.2 }],
    logic: "AND",
    direction: "AUTO",
    atrStopMultiple: 1,
    takeProfitMultiple: 2,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
  {
    id: "cci_extreme",
    name: "CCI Extreme Reversal",
    description: "Fade CCI readings beyond ±100",
    entryRules: [{ indicator: "CCI_20", operator: "<", value: -100 }],
    exitRules: [{ indicator: "CCI_20", operator: ">", value: 0 }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 1.5,
    takeProfitMultiple: 2,
    riskPerTradePct: 0.75,
    maxBarsInTrade: 0,
  },
  {
    id: "mfi_reversal",
    name: "MFI Volume Reversal",
    description: "Volume-weighted RSI oversold reversal",
    entryRules: [{ indicator: "MFI_14", operator: "<", value: 20 }],
    exitRules: [{ indicator: "MFI_14", operator: ">", value: 60 }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 1.5,
    takeProfitMultiple: 2.2,
    riskPerTradePct: 0.75,
    maxBarsInTrade: 0,
  },
  {
    id: "fisher_extreme",
    name: "Fisher Transform Extreme",
    description: "Ehlers reversal from an extreme Fisher reading",
    entryRules: [
      { indicator: "FISHER_TRANSFORM", operator: ">", value: -1.5 },
      { indicator: "FISHER_TRANSFORM", operator: "<", value: 0 },
    ],
    exitRules: [{ indicator: "FISHER_TRANSFORM", operator: ">", value: 1 }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 1.3,
    takeProfitMultiple: 2,
    riskPerTradePct: 0.75,
    maxBarsInTrade: 0,
  },
  {
    id: "hull_ma",
    name: "Hull MA Momentum",
    description: "Low-lag Hull MA trend follow",
    entryRules: [
      { indicator: "HMA_20", operator: "<", value: "CLOSE" },
      { indicator: "RSI_14", operator: ">", value: 50 },
    ],
    exitRules: [{ indicator: "HMA_20", operator: ">", value: "CLOSE" }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 1.5,
    takeProfitMultiple: 2.2,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
  {
    id: "donchian",
    name: "Donchian Breakout",
    description: "Turtle-style breakout through the rolling high",
    entryRules: [{ indicator: "DONCHIAN_UPPER", operator: "<=", value: "CLOSE" }],
    exitRules: [{ indicator: "DONCHIAN_MIDDLE", operator: ">", value: "CLOSE" }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 2,
    takeProfitMultiple: 3,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
  {
    id: "keltner",
    name: "Keltner Channel Breakout",
    description: "Volatility-expansion breakout through the upper Keltner",
    entryRules: [
      { indicator: "KC_UPPER", operator: "<", value: "CLOSE" },
      { indicator: "VOLUME_RATIO", operator: ">", value: 1.1 },
    ],
    exitRules: [{ indicator: "KC_MIDDLE", operator: ">", value: "CLOSE" }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 1.8,
    takeProfitMultiple: 2.5,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
  {
    id: "zscore_fade",
    name: "Mean Reversion Z-Score",
    description: "Fade a statistically extreme deviation",
    entryRules: [{ indicator: "MEAN_REVERSION_Z", operator: "<", value: -1.8 }],
    exitRules: [{ indicator: "MEAN_REVERSION_Z", operator: ">", value: 0 }],
    logic: "AND",
    direction: "BUY",
    atrStopMultiple: 1.5,
    takeProfitMultiple: 2,
    riskPerTradePct: 0.75,
    maxBarsInTrade: 0,
  },
  {
    id: "volume_breakout",
    name: "Volume Breakout",
    description: "High-volume close through the upper band",
    entryRules: [
      { indicator: "VOLUME_RATIO", operator: ">", value: 1.5 },
      { indicator: "BB_PERCENT", operator: ">", value: 0.9 },
    ],
    exitRules: [{ indicator: "VOLUME_RATIO", operator: "<", value: 0.7 }],
    logic: "AND",
    direction: "AUTO",
    atrStopMultiple: 1.5,
    takeProfitMultiple: 2,
    riskPerTradePct: 1,
    maxBarsInTrade: 0,
  },
];
