import AsyncStorage from '@react-native-async-storage/async-storage';
import { createWebhookSignature } from './security';
import { getRecoveryReadiness } from './queueBackup';
import { getRegionalWorkerStatus } from './worker';
export type AlertKind = 'replication_lag' | 'backup_failure' | 'failover' | 'worker_dead_letter';
export type AlertRule = { id: string; workspaceId: string; kind: AlertKind; enabled: boolean; threshold: number; cooldownMs: number; webhookUrl: string; secret: string; lastTriggeredAt?: string };
export type AlertIncident = { id: string; kind: AlertKind; severity: 'warning' | 'critical'; status: 'open' | 'resolved'; message: string; value: number; threshold: number; regionId?: string; createdAt: string; resolvedAt?: string };
export type WebhookDelivery = { id: string; alertId: string; url: string; status: 'sent' | 'failed' | 'retrying'; attempts: number; statusCode?: number; error?: string; createdAt: string; lastAttemptAt: string };
const RULES_KEY = 'nova.alerting.rules.v1';
const INCIDENTS_KEY = 'nova.alerting.incidents.v1';
const DELIVERIES_KEY = 'nova.alerting.deliveries.v1';
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();
async function load<T>(key: string, fallback: T) { return parse<T>(await AsyncStorage.getItem(key), fallback); }
async function save<T>(key: string, value: T) { await AsyncStorage.setItem(key, JSON.stringify(value)); return value; }
export async function loadAlertRules() { return load<AlertRule[]>(RULES_KEY, []); }
export async function saveAlertRule(rule: Omit<AlertRule, 'id'> & { id?: string }) { const rules = await loadAlertRules(); const next = { ...rule, id: rule.id ?? id('rule') }; await save(RULES_KEY, [next, ...rules.filter((item) => item.id !== next.id)]); return next; }
export async function loadAlertIncidents() { return load<AlertIncident[]>(INCIDENTS_KEY, []); }
export async function loadWebhookDeliveries() { return load<WebhookDelivery[]>(DELIVERIES_KEY, []); }
async function sendWebhook(rule: AlertRule, incident: AlertIncident) { const payload = JSON.stringify({ event: 'nova.alert', alert: incident, sentAt: now() }); const delivery: WebhookDelivery = { id: id('delivery'), alertId: incident.id, url: rule.webhookUrl, status: 'retrying', attempts: 0, createdAt: now(), lastAttemptAt: now() }; const deliveries = await loadWebhookDeliveries(); for (let attempt = 1; attempt <= 3; attempt += 1) { delivery.attempts = attempt; delivery.lastAttemptAt = now(); try { const response = await fetch(rule.webhookUrl, { method: 'POST', headers: { 'content-type': 'application/json', 'x-nova-signature': createWebhookSignature(payload, rule.secret), 'x-nova-alert-id': incident.id, 'x-nova-attempt': String(attempt) }, body: payload }); delivery.statusCode = response.status; if (response.ok) { delivery.status = 'sent'; delivery.error = undefined; break; } delivery.error = `HTTP ${response.status}`; } catch (error) { delivery.error = error instanceof Error ? error.message : 'Webhook delivery failed'; } if (attempt < 3) await new Promise((resolve) => setTimeout(resolve, 2 ** attempt * 100)); } if (delivery.status !== 'sent') delivery.status = 'failed'; await save(DELIVERIES_KEY, [delivery, ...deliveries].slice(0, 500)); return delivery; }
export async function evaluateAlerting(workspaceId = 'nova-local') { const [rules, incidents, status, readiness] = await Promise.all([loadAlertRules(), loadAlertIncidents(), getRegionalWorkerStatus(), getRecoveryReadiness()]); const candidates: Array<{ rule: AlertRule; value: number; message: string; regionId?: string }> = []; for (const rule of rules.filter((item) => item.enabled && item.workspaceId === workspaceId)) { if (rule.kind === 'replication_lag') { const region = status.regions.find((item) => item.lag >= rule.threshold); if (region) candidates.push({ rule, value: region.lag, regionId: region.id, message: `Replication lag is ${region.lag} entries in ${region.id}.` }); } if (rule.kind === 'backup_failure' && !readiness.ready) candidates.push({ rule, value: readiness.backupCount, message: 'No usable worker queue backup is available.' }); } const created: AlertIncident[] = []; const updatedRules: AlertRule[] = []; for (const candidate of candidates) { const recent = candidate.rule.lastTriggeredAt && Date.now() - new Date(candidate.rule.lastTriggeredAt).getTime() < candidate.rule.cooldownMs; if (recent) { updatedRules.push(candidate.rule); continue; } const incident: AlertIncident = { id: id('incident'), kind: candidate.rule.kind, severity: candidate.value >= candidate.rule.threshold * 2 ? 'critical' : 'warning', status: 'open', message: candidate.message, value: candidate.value, threshold: candidate.rule.threshold, regionId: candidate.regionId, createdAt: now() }; await sendWebhook(candidate.rule, incident); created.push(incident); updatedRules.push({ ...candidate.rule, lastTriggeredAt: incident.createdAt }); } if (created.length) await save(INCIDENTS_KEY, [...created, ...incidents].slice(0, 500)); if (updatedRules.length) { const allRules = await loadAlertRules(); await save(RULES_KEY, allRules.map((rule) => updatedRules.find((item) => item.id === rule.id) ?? rule)); } return { incidents: created, checkedRules: rules.length, deliveryCount: (await loadWebhookDeliveries()).length }; }
export async function resolveIncident(idValue: string) { const incidents = await loadAlertIncidents(); const next = incidents.map((incident) => incident.id === idValue ? { ...incident, status: 'resolved' as const, resolvedAt: now() } : incident); await save(INCIDENTS_KEY, next); return next.find((incident) => incident.id === idValue); }
export async function alertingSnapshot() { return { rules: await loadAlertRules(), incidents: await loadAlertIncidents(), deliveries: await loadWebhookDeliveries() }; }
