import { aggregateUsage, bootstrapWorkspace, checkConnectors, createDefaultWorkflow, createProjectPlan, runWorkflow, triageTask } from './services';
import { getServerSnapshot, loadBackendStore } from './repository';
import { buildSearchIndex, searchIndex } from './search';

export type ApiRequest = { method: 'GET' | 'POST' | 'PATCH'; path: string; workspaceId: string; actorId?: string; body?: Record<string, unknown> };
export type ApiResponse = { status: number; data: unknown; requestId: string };
const requestId = () => `req-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const text = (body: Record<string, unknown> | undefined, key: string) => typeof body?.[key] === 'string' ? String(body[key]) : '';

export async function handleLocalApi(request: ApiRequest): Promise<ApiResponse> { const id = requestId(); try { const actorId = request.actorId ?? 'local-user'; if (request.method === 'GET' && request.path === '/health') return { status: 200, requestId: id, data: { status: 'ok', version: 'nova-local-backend-1', requestId: id } }; if (request.method === 'GET' && request.path === '/v1/snapshot') return { status: 200, requestId: id, data: await getServerSnapshot(request.workspaceId) }; if (request.method === 'POST' && request.path === '/v1/bootstrap') return { status: 201, requestId: id, data: await bootstrapWorkspace(request.workspaceId, actorId) }; if (request.method === 'POST' && request.path === '/v1/projects/plan') return { status: 201, requestId: id, data: await createProjectPlan(request.workspaceId, actorId, text(request.body, 'name') || 'Untitled project', text(request.body, 'description') || 'Created from Nova.') }; if (request.method === 'POST' && request.path === '/v1/workflows/default') return { status: 201, requestId: id, data: await createDefaultWorkflow(request.workspaceId) }; if (request.method === 'POST' && request.path.startsWith('/v1/workflows/') && request.path.endsWith('/run')) return { status: 200, requestId: id, data: await runWorkflow(request.path.split('/')[3], request.workspaceId, actorId) }; if (request.method === 'PATCH' && request.path.startsWith('/v1/tasks/')) return { status: 200, requestId: id, data: await triageTask(request.path.split('/')[3], (request.body?.status as never) ?? 'todo', actorId, request.workspaceId) }; if (request.method === 'GET' && request.path === '/v1/connectors/check') return { status: 200, requestId: id, data: await checkConnectors(request.workspaceId) }; if (request.method === 'GET' && request.path === '/v1/usage') return { status: 200, requestId: id, data: await aggregateUsage(request.workspaceId) }; if (request.method === 'GET' && request.path === '/v1/search') { const store = await loadBackendStore(); const index = buildSearchIndex({ files: [], memories: [], projects: store.projects, tasks: store.tasks, runs: [] }, request.workspaceId); return { status: 200, requestId: id, data: searchIndex(index, text(request.body, 'query')) }; } return { status: 404, requestId: id, data: { message: `No local handler for ${request.method} ${request.path}` } }; } catch (error) { return { status: 500, requestId: id, data: { message: error instanceof Error ? error.message : 'Local backend error' } }; } }
