import AsyncStorage from '@react-native-async-storage/async-storage';
import { BackendEvent } from './contracts';
import { appendAudit, queueNotification } from './repository';

export type ScheduleRecord = { id: string; workspaceId: string; name: string; toolId: string; input: Record<string, unknown>; cadence: 'hourly' | 'daily' | 'weekly' | 'manual'; enabled: boolean; nextRunAt: string; lastRunAt?: string; createdAt: string };
export type WebhookSubscription = { id: string; workspaceId: string; name: string; eventTypes: string[]; route: string; enabled: boolean; secretHint: string; deliveries: number; lastDeliveryAt?: string; createdAt: string };
export type AutomationRun = { id: string; scheduleId?: string; workflowId?: string; status: 'queued' | 'running' | 'completed' | 'failed'; startedAt: string; finishedAt?: string; output?: unknown; error?: string };
const SCHEDULES_KEY = 'nova.backend.automation.schedules.v1';
const WEBHOOKS_KEY = 'nova.backend.automation.webhooks.v1';
const RUNS_KEY = 'nova.backend.automation.runs.v1';
const EVENTS_KEY = 'nova.backend.automation.replay-events.v1';
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const makeId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();
const nextCadence = (cadence: ScheduleRecord['cadence']) => { const date = new Date(); if (cadence === 'hourly') date.setHours(date.getHours() + 1); else if (cadence === 'daily') date.setDate(date.getDate() + 1); else if (cadence === 'weekly') date.setDate(date.getDate() + 7); else date.setMinutes(date.getMinutes() + 5); return date.toISOString(); };
export async function loadSchedules() { return parse<ScheduleRecord[]>(await AsyncStorage.getItem(SCHEDULES_KEY), []); }
export async function saveSchedules(items: ScheduleRecord[]) { await AsyncStorage.setItem(SCHEDULES_KEY, JSON.stringify(items)); return items; }
export async function createSchedule(input: Pick<ScheduleRecord, 'workspaceId' | 'name' | 'toolId' | 'input' | 'cadence'>) { const schedule: ScheduleRecord = { ...input, id: makeId('schedule'), enabled: true, nextRunAt: nextCadence(input.cadence), createdAt: now() }; return saveSchedules([schedule, ...(await loadSchedules())]).then((items) => items[0]); }
export async function toggleSchedule(id: string) { const items = await loadSchedules(); const next = items.map((item) => item.id === id ? { ...item, enabled: !item.enabled } : item); await saveSchedules(next); return next.find((item) => item.id === id); }
export async function loadWebhookSubscriptions() { return parse<WebhookSubscription[]>(await AsyncStorage.getItem(WEBHOOKS_KEY), []); }
export async function createWebhookSubscription(input: Pick<WebhookSubscription, 'workspaceId' | 'name' | 'eventTypes' | 'route'>) { const item: WebhookSubscription = { ...input, id: makeId('hook'), enabled: true, secretHint: `whsec_${Math.random().toString(36).slice(2, 8)}`, deliveries: 0, createdAt: now() }; const next = [item, ...(await loadWebhookSubscriptions())]; await AsyncStorage.setItem(WEBHOOKS_KEY, JSON.stringify(next)); return item; }
export async function toggleWebhook(id: string) { const items = await loadWebhookSubscriptions(); const next = items.map((item) => item.id === id ? { ...item, enabled: !item.enabled } : item); await AsyncStorage.setItem(WEBHOOKS_KEY, JSON.stringify(next)); return next.find((item) => item.id === id); }
export async function loadAutomationRuns() { return parse<AutomationRun[]>(await AsyncStorage.getItem(RUNS_KEY), []); }
export async function runSchedule(schedule: ScheduleRecord, actorId = 'local-automation') { const run: AutomationRun = { id: makeId('automation-run'), scheduleId: schedule.id, status: 'running', startedAt: now() }; const runs = [run, ...(await loadAutomationRuns())]; await AsyncStorage.setItem(RUNS_KEY, JSON.stringify(runs)); await appendAudit({ workspaceId: schedule.workspaceId, actorId, action: 'schedule.started', resource: 'schedule', resourceId: schedule.id, risk: 'low', metadata: { toolId: schedule.toolId } }); await queueNotification({ workspaceId: schedule.workspaceId, channel: 'local', title: 'Automation queued', body: `${schedule.name} is ready for ${schedule.toolId}.`, route: '/automation' }); const completed: AutomationRun = { ...run, status: 'completed', finishedAt: now(), output: { toolId: schedule.toolId, input: schedule.input } }; await AsyncStorage.setItem(RUNS_KEY, JSON.stringify([completed, ...runs.slice(1)])); const schedules = await loadSchedules(); await saveSchedules(schedules.map((item) => item.id === schedule.id ? { ...item, lastRunAt: completed.finishedAt, nextRunAt: nextCadence(item.cadence) } : item)); return completed; }
export async function saveReplayEvent(event: BackendEvent) { const events = parse<BackendEvent[]>(await AsyncStorage.getItem(EVENTS_KEY), []); const next = [event, ...events.filter((item) => item.id !== event.id)].slice(0, 1000); await AsyncStorage.setItem(EVENTS_KEY, JSON.stringify(next)); return event; }
export async function loadReplayEvents() { return parse<BackendEvent[]>(await AsyncStorage.getItem(EVENTS_KEY), []); }
export async function replayEvent(event: BackendEvent, actorId = 'local-replay') { await saveReplayEvent({ ...event, id: makeId('replay'), createdAt: now() }); await appendAudit({ workspaceId: 'nova-local', actorId, action: 'event.replayed', resource: 'event', resourceId: event.id, risk: 'medium', metadata: { type: event.type } }); return event; }
