import { executeFailover, heartbeatRegion, loadReplicationState, planFailover, replicatePending } from './regions';
import { createQueueBackup, getRecoveryReadiness, recoverQueuePointInTime } from './queueBackup';
import { enqueueWorkerJob, loadWorkerQueue, processWorkerQueueRegional } from './worker';
export type ChaosScenario = 'primary-outage' | 'replication-lag' | 'lease-contention' | 'backup-recovery' | 'worker-dead-letter';
export type ChaosStep = { name: string; status: 'passed' | 'failed'; durationMs: number; detail?: string };
export type ChaosReport = { id: string; scenario: ChaosScenario; startedAt: string; completedAt: string; passed: boolean; steps: ChaosStep[]; promotedRegion?: string; recoveredQueue?: number };
const id = () => `chaos-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();
async function step(name: string, action: () => Promise<string | void>): Promise<ChaosStep> { const started = Date.now(); try { const detail = await action(); return { name, status: 'passed', durationMs: Date.now() - started, detail: detail ?? undefined }; } catch (error) { return { name, status: 'failed', durationMs: Date.now() - started, detail: error instanceof Error ? error.message : 'chaos step failed' }; } }
export async function runChaosScenario(scenario: ChaosScenario, workspaceId = 'nova-chaos'): Promise<ChaosReport> { const startedAt = now(); const steps: ChaosStep[] = []; let promotedRegion: string | undefined; let recoveredQueue: number | undefined; if (scenario === 'primary-outage') { steps.push(await step('mark primary unavailable', async () => { const state = await loadReplicationState(); await heartbeatRegion(state.primaryRegion, 0, false); })); steps.push(await step('plan and execute promotion', async () => { const plan = await planFailover(workspaceId, 'chaos primary outage'); const result = await executeFailover(plan); promotedRegion = result.state.primaryRegion; })); steps.push(await step('verify promoted worker lease', async () => { const result = await processWorkerQueueRegional(workspaceId, promotedRegion ?? 'eu-west-1', { autoFailover: false }); return `${result.role}:${result.regionId}`; })); }
  if (scenario === 'replication-lag') { steps.push(await step('inject standby lag', async () => { const state = await loadReplicationState(); await heartbeatRegion(state.regions.find((region) => region.id !== state.primaryRegion)?.id ?? 'eu-west-1', 0, false); })); steps.push(await step('detect lagged region', async () => { const status = await loadReplicationState(); const lagged = status.regions.find((region) => region.status === 'unavailable'); if (!lagged) throw new Error('No lagged region detected'); return lagged.id; })); }
  if (scenario === 'lease-contention') { steps.push(await step('acquire primary lease', async () => { const { acquireLeaderLease } = await import('./regions'); await acquireLeaderLease(workspaceId, 'us-east-1', 30_000); })); steps.push(await step('reject competing lease', async () => { const { acquireLeaderLease } = await import('./regions'); try { await acquireLeaderLease(workspaceId, 'eu-west-1', 30_000); throw new Error('Competing lease was accepted'); } catch (error) { if (!(error instanceof Error) || !error.message.includes('Leader lease')) throw error; return 'contention rejected'; } })); }
  if (scenario === 'backup-recovery') { steps.push(await step('create queue backup', async () => { await enqueueWorkerJob({ toolId: 'workspace-health', input: { workspaceId } }); await createQueueBackup('us-east-1', ['eu-west-1']); })); steps.push(await step('verify recovery readiness', async () => { const readiness = await getRecoveryReadiness(); if (!readiness.ready) throw new Error('Recovery not ready'); })); steps.push(await step('restore point in time', async () => { const readiness = await getRecoveryReadiness(); const backups = await import('./queueBackup').then((module) => module.loadQueueBackups()); const backup = backups.at(-1); if (!backup) throw new Error('No backup available'); const result = await recoverQueuePointInTime(backup.createdAt, readiness.latestSequence); recoveredQueue = result.restoredQueue; return `${result.restoredQueue} queue items restored`; })); }
  if (scenario === 'worker-dead-letter') { steps.push(await step('enqueue poison job', async () => { await enqueueWorkerJob({ toolId: 'chaos-unknown-tool', input: {}, maxAttempts: 1 }); })); steps.push(await step('verify dead-letter handling', async () => { const result = await processWorkerQueueRegional(workspaceId, 'us-east-1', { autoFailover: false }); if (!result.deadLettered.length) throw new Error('Poison job was not dead-lettered'); return `${result.deadLettered.length} dead-lettered`; })); }
  const completedAt = now(); return { id: id(), scenario, startedAt, completedAt, passed: steps.every((item) => item.status === 'passed'), steps, promotedRegion, recoveredQueue };
}
export async function runChaosMatrix(workspaceId = 'nova-chaos') { const scenarios: ChaosScenario[] = ['primary-outage', 'replication-lag', 'lease-contention', 'backup-recovery', 'worker-dead-letter']; const reports: ChaosReport[] = []; for (const scenario of scenarios) reports.push(await runChaosScenario(scenario, workspaceId)); return { passed: reports.every((report) => report.passed), reports }; }
