import AsyncStorage from '@react-native-async-storage/async-storage';
import { BackendConfig, BackendEvent, BackendHealth, BackendJob, BackendMutation, BackendToolDescriptor, defaultBackendConfig, SyncEnvelope, SyncResult } from './contracts';

const CONFIG_KEY = 'nova.backend.config.v1';
const OUTBOX_KEY = 'nova.backend.outbox.v1';
const CURSOR_KEY = 'nova.backend.cursor.v1';
const CLIENT_ID_KEY = 'nova.backend.client-id.v1';

const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const makeId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

export async function loadBackendConfig(): Promise<BackendConfig> { return { ...defaultBackendConfig, ...parse<Partial<BackendConfig>>(await AsyncStorage.getItem(CONFIG_KEY), {}) }; }
export async function saveBackendConfig(config: BackendConfig) { const baseUrl = config.baseUrl.trim().replace(/\/$/, ''); if (config.mode === 'remote' && baseUrl) { let parsed: URL; try { parsed = new URL(baseUrl); } catch { throw new Error('Backend URL must be a valid URL.'); } const local = parsed.hostname === 'localhost' || parsed.hostname === '127.0.0.1'; if (parsed.protocol !== 'https:' && !local) throw new Error('Remote backend URLs must use HTTPS.'); } const safe = { ...config, baseUrl }; await AsyncStorage.setItem(CONFIG_KEY, JSON.stringify(safe)); return safe; }
export async function getClientId() { const existing = await AsyncStorage.getItem(CLIENT_ID_KEY); if (existing) return existing; const created = makeId('client'); await AsyncStorage.setItem(CLIENT_ID_KEY, created); return created; }
export async function loadOutbox() { return parse<BackendMutation[]>(await AsyncStorage.getItem(OUTBOX_KEY), []); }
export async function saveOutbox(outbox: BackendMutation[]) { await AsyncStorage.setItem(OUTBOX_KEY, JSON.stringify(outbox.slice(-300))); }
export async function enqueueMutation(kind: BackendMutation['kind'], payload: unknown, error?: string) { const outbox = await loadOutbox(); const mutation: BackendMutation = { id: makeId('mutation'), kind, payload, attempts: 0, nextAttemptAt: new Date().toISOString(), createdAt: new Date().toISOString(), lastError: error }; await saveOutbox([...outbox, mutation]); return mutation; }

export class BackendClient {
  constructor(private readonly config: BackendConfig) {}
  get enabled() { return this.config.mode === 'remote' && Boolean(this.config.baseUrl); }
  private async request<T>(path: string, init: RequestInit = {}): Promise<T> { if (!this.enabled) throw new Error('Remote backend is disabled.'); const headers = new Headers(init.headers); headers.set('Accept', 'application/json'); headers.set('Content-Type', 'application/json'); if (this.config.apiToken) headers.set('Authorization', `Bearer ${this.config.apiToken}`); const response = await fetch(`${this.config.baseUrl}${path}`, { ...init, headers }); const body = await response.text(); const parsed = body ? parse<unknown>(body, body) : undefined; if (!response.ok) throw new Error(typeof parsed === 'object' && parsed && 'message' in parsed ? String((parsed as { message: unknown }).message) : `Backend request failed with ${response.status}`); return parsed as T; }
  async health(): Promise<BackendHealth> { const started = Date.now(); if (!this.enabled) return { status: 'offline', checkedAt: new Date().toISOString(), message: 'Offline mode is active; local tools remain available.' }; try { const result = await this.request<{ version?: string; status?: string }>('/health'); return { status: 'healthy', latencyMs: Date.now() - started, version: result.version, checkedAt: new Date().toISOString(), message: 'Remote backend is reachable.' }; } catch (error) { return { status: 'error', latencyMs: Date.now() - started, checkedAt: new Date().toISOString(), message: error instanceof Error ? error.message : 'Backend health check failed.' }; } }
  async listTools() { return this.request<BackendToolDescriptor[]>('/v1/tools'); }
  async sync(envelope: SyncEnvelope) { return this.request<SyncResult>('/v1/sync', { method: 'POST', body: JSON.stringify(envelope) }); }
  async dispatchTool(toolId: string, input: Record<string, unknown>) { return this.request<BackendJob>('/v1/jobs', { method: 'POST', body: JSON.stringify({ toolId, input, workspaceId: this.config.workspaceId }) }); }
  async ingestEvents(events: BackendEvent[]) { return this.request<{ accepted: number }>('/v1/events', { method: 'POST', body: JSON.stringify({ workspaceId: this.config.workspaceId, events }) }); }
}

export async function syncWithBackend(files: unknown[], events: BackendEvent[]) { const config = await loadBackendConfig(); const client = new BackendClient(config); if (!client.enabled) return { mode: 'offline' as const, result: null }; const clientId = await getClientId(); const cursor = await AsyncStorage.getItem(CURSOR_KEY) ?? undefined; try { const result = await client.sync({ clientId, workspaceId: config.workspaceId, cursor, files, events, sentAt: new Date().toISOString() }); if (result.cursor) await AsyncStorage.setItem(CURSOR_KEY, result.cursor); return { mode: 'remote' as const, result }; } catch (error) { await enqueueMutation('sync', { files, events }, error instanceof Error ? error.message : 'sync failed'); throw error; } }

export async function flushOutbox() { const config = await loadBackendConfig(); const client = new BackendClient(config); if (!client.enabled) return { flushed: 0, remaining: (await loadOutbox()).length }; const outbox = await loadOutbox(); let flushed = 0; const remaining: BackendMutation[] = []; for (const mutation of outbox) { if (new Date(mutation.nextAttemptAt).getTime() > Date.now()) { remaining.push(mutation); continue; } try { if (mutation.kind === 'sync') { const payload = mutation.payload as { files: unknown[]; events: BackendEvent[] }; await syncWithBackend(payload.files, payload.events); } else if (mutation.kind === 'event') await client.ingestEvents(mutation.payload as BackendEvent[]); else { const payload = mutation.payload as { toolId: string; input: Record<string, unknown> }; await client.dispatchTool(payload.toolId, payload.input); } flushed += 1; } catch (error) { const attempts = mutation.attempts + 1; if (attempts < 5) remaining.push({ ...mutation, attempts, nextAttemptAt: new Date(Date.now() + Math.min(60 * 60_000, 2 ** attempts * 10_000)).toISOString(), lastError: error instanceof Error ? error.message : 'retry failed' }); } } await saveOutbox(remaining); return { flushed, remaining: remaining.length }; }
