import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { aggregateUsage, bootstrapWorkspace, checkConnectors, createDefaultWorkflow, createProjectPlan, runWorkflow, toggleWorkflow, triageTask } from './services';
import { AuditRecord, ConnectorRecord, ProjectRecord, TaskRecord, UsageMetric, WorkflowRecord } from './domain';
import { loadBackendStore } from './repository';
import { processWorkerQueue } from './worker';

type DomainContextValue = { projects: ProjectRecord[]; tasks: TaskRecord[]; workflows: WorkflowRecord[]; connectors: ConnectorRecord[]; audit: AuditRecord[]; usage: UsageMetric[]; summary: { runs: number; toolCalls: number; filesIndexed: number; syncs: number; errors: number; avgLatencyMs: number }; ready: boolean; refresh: () => Promise<void>; createPlan: (name: string, description: string) => Promise<void>; seedWorkspace: () => Promise<void>; addDefaultWorkflow: () => Promise<void>; runWorkflow: (id: string) => Promise<void>; toggleWorkflow: (id: string) => Promise<void>; triageTask: (id: string, status: TaskRecord['status']) => Promise<void>; checkConnectors: () => Promise<void>; processJobs: () => Promise<void> };
const Context = createContext<DomainContextValue | null>(null);
export function DomainProvider({ children }: { children: React.ReactNode }) { const [store, setStore] = useState<Awaited<ReturnType<typeof loadBackendStore>>>({ projects: [], tasks: [], workflows: [], connectors: [], audit: [], usage: [], notifications: [] }); const [summary, setSummary] = useState({ runs: 0, toolCalls: 0, filesIndexed: 0, syncs: 0, errors: 0, avgLatencyMs: 0 }); const [ready, setReady] = useState(false); const refresh = async () => { const next = await loadBackendStore(); setStore(next); setSummary(await aggregateUsage('nova-local')); setReady(true); }; useEffect(() => { void refresh(); }, []); const seedWorkspace = async () => { await bootstrapWorkspace('nova-local'); await refresh(); }; const createPlan = async (name: string, description: string) => { await createProjectPlan('nova-local', 'local-user', name, description); await refresh(); }; const addDefaultWorkflow = async () => { await createDefaultWorkflow('nova-local'); await refresh(); }; const executeWorkflow = async (id: string) => { await runWorkflow(id, 'nova-local', 'local-user'); await refresh(); }; const flipWorkflow = async (id: string) => { await toggleWorkflow(id); await refresh(); }; const updateTask = async (id: string, status: TaskRecord['status']) => { await triageTask(id, status, 'local-user', 'nova-local'); await refresh(); }; const refreshConnectors = async () => { await checkConnectors('nova-local'); await refresh(); }; const processJobs = async () => { await processWorkerQueue('nova-local'); await refresh(); }; const value = useMemo(() => ({ projects: store.projects, tasks: store.tasks, workflows: store.workflows, connectors: store.connectors, audit: store.audit, usage: store.usage, summary, ready, refresh, createPlan, seedWorkspace, addDefaultWorkflow, runWorkflow: executeWorkflow, toggleWorkflow: flipWorkflow, triageTask: updateTask, checkConnectors: refreshConnectors, processJobs }), [store, summary, ready]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useDomain() { const value = useContext(Context); if (!value) throw new Error('useDomain must be used inside DomainProvider'); return value; }
