import AsyncStorage from '@react-native-async-storage/async-storage';
export type TraceStatus = 'ok' | 'error';
export type TraceSpan = { traceId: string; spanId: string; parentSpanId?: string; name: string; regionId?: string; startedAt: string; endedAt?: string; durationMs?: number; status: TraceStatus; attributes: Record<string, string | number | boolean> };
export type PerformanceMetric = { id: string; name: 'worker.duration' | 'worker.completed' | 'worker.failed' | 'replication.latency' | 'replication.lag' | 'failover.duration' | 'backup.duration' | 'recovery.duration'; value: number; unit: 'ms' | 'count' | 'entries'; regionId?: string; workspaceId?: string; recordedAt: string; traceId?: string };
export type MetricSummary = { name: PerformanceMetric['name']; count: number; total: number; min: number; max: number; average: number; p95: number; unit: PerformanceMetric['unit'] };
const SPAN_KEY = 'nova.observability.spans.v1';
const METRIC_KEY = 'nova.observability.metrics.v1';
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
const now = () => new Date().toISOString();
export async function loadSpans() { return parse<TraceSpan[]>(await AsyncStorage.getItem(SPAN_KEY), []); }
export async function loadMetrics() { return parse<PerformanceMetric[]>(await AsyncStorage.getItem(METRIC_KEY), []); }
async function saveSpans(spans: TraceSpan[]) { await AsyncStorage.setItem(SPAN_KEY, JSON.stringify(spans.slice(-2000))); return spans; }
async function saveMetrics(metrics: PerformanceMetric[]) { await AsyncStorage.setItem(METRIC_KEY, JSON.stringify(metrics.slice(-5000))); return metrics; }
export async function startSpan(name: string, attributes: TraceSpan['attributes'] = {}, parent?: { traceId: string; spanId: string }, regionId?: string) { const span: TraceSpan = { traceId: parent?.traceId ?? id('trace'), spanId: id('span'), parentSpanId: parent?.spanId, name, regionId, startedAt: now(), status: 'ok', attributes }; await saveSpans([...(await loadSpans()), span]); return span; }
export async function endSpan(span: TraceSpan, status: TraceStatus = 'ok', attributes: TraceSpan['attributes'] = {}) { const endedAt = now(); const durationMs = Math.max(0, new Date(endedAt).getTime() - new Date(span.startedAt).getTime()); const next = { ...span, endedAt, durationMs, status, attributes: { ...span.attributes, ...attributes } }; const spans = (await loadSpans()).map((item) => item.spanId === span.spanId ? next : item); await saveSpans(spans); return next; }
export async function recordMetric(input: Omit<PerformanceMetric, 'id' | 'recordedAt'>) { const metric: PerformanceMetric = { ...input, id: id('metric'), recordedAt: now() }; await saveMetrics([...(await loadMetrics()), metric]); return metric; }
export async function summarizeMetrics(regionId?: string, workspaceId?: string): Promise<MetricSummary[]> { const metrics = (await loadMetrics()).filter((item) => (!regionId || item.regionId === regionId) && (!workspaceId || item.workspaceId === workspaceId)); const grouped = new Map<string, PerformanceMetric[]>(); for (const metric of metrics) grouped.set(metric.name, [...(grouped.get(metric.name) ?? []), metric]); return [...grouped.entries()].map(([name, values]) => { const sorted = values.map((item) => item.value).sort((a, b) => a - b); const p95 = sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * 0.95))] ?? 0; return { name: name as PerformanceMetric['name'], count: values.length, total: values.reduce((sum, item) => sum + item.value, 0), min: sorted[0] ?? 0, max: sorted.at(-1) ?? 0, average: values.length ? values.reduce((sum, item) => sum + item.value, 0) / values.length : 0, p95, unit: values[0]?.unit ?? 'count' }; }); }
export async function clearObservability() { await AsyncStorage.removeItem(SPAN_KEY); await AsyncStorage.removeItem(METRIC_KEY); }
export async function exportObservability() { return { exportedAt: now(), spans: await loadSpans(), metrics: await loadMetrics(), summaries: await summarizeMetrics() }; }
