import AsyncStorage from '@react-native-async-storage/async-storage';
import { loadDeadLetters, loadWorkerQueue, WorkerJob } from './worker';
import { loadReplicationState, ReplicationState, saveReplicationState } from './regions';
import { endSpan, recordMetric, startSpan } from './observability';
export type QueueBackup = { id: string; createdAt: string; sourceRegion: string; targetRegions: string[]; queue: WorkerJob[]; deadLetters: WorkerJob[]; replicationSequence: number; checksum: string; status: 'complete' | 'partial' | 'failed' };
export type RecoveryResult = { backupId: string; restoredQueue: number; restoredDeadLetters: number; targetTime: string; targetSequence: number; sourceRegion: string };
const BACKUP_KEY = 'nova.backend.queue-backups.v1';
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();
const checksum = (queue: WorkerJob[], dead: WorkerJob[], seq: number) => `${queue.length}:${dead.length}:${seq}:${JSON.stringify(queue).length + JSON.stringify(dead).length}`;
export async function loadQueueBackups() { return parse<QueueBackup[]>(await AsyncStorage.getItem(BACKUP_KEY), []); }
async function saveQueueBackups(backups: QueueBackup[]) { await AsyncStorage.setItem(BACKUP_KEY, JSON.stringify(backups.slice(-100))); return backups; }
export async function createQueueBackup(sourceRegion: string, targetRegions: string[] = []): Promise<QueueBackup> { const span = await startSpan('queue.backup', { sourceRegion, targetCount: targetRegions.length }, undefined, sourceRegion); const started = Date.now(); try { const [queue, deadLetters, replication] = await Promise.all([loadWorkerQueue(), loadDeadLetters(), loadReplicationState()]); const backup: QueueBackup = { id: id('backup'), createdAt: now(), sourceRegion, targetRegions, queue, deadLetters, replicationSequence: replication.lastSequence, checksum: checksum(queue, deadLetters, replication.lastSequence), status: targetRegions.length ? 'complete' : 'partial' }; await saveQueueBackups([...(await loadQueueBackups()), backup]); await recordMetric({ name: 'backup.duration', value: Date.now() - started, unit: 'ms', regionId: sourceRegion, traceId: span.traceId }); await endSpan(span, 'ok', { queueSize: queue.length, deadLetterSize: deadLetters.length }); return backup; } catch (error) { await endSpan(span, 'error', { error: error instanceof Error ? error.message : 'backup-failed' }); throw error; } }
export async function replicateQueueBackup(backupId: string, targetRegion: string) { const backups = await loadQueueBackups(); const backup = backups.find((item) => item.id === backupId); if (!backup) throw new Error('Queue backup not found.'); const updated = { ...backup, targetRegions: [...new Set([...backup.targetRegions, targetRegion])], status: 'complete' as const }; await saveQueueBackups(backups.map((item) => item.id === backupId ? updated : item)); return updated; }
export async function recoverQueuePointInTime(targetTime: string, targetSequence?: number): Promise<RecoveryResult> { const backups = (await loadQueueBackups()).filter((backup) => new Date(backup.createdAt).getTime() <= new Date(targetTime).getTime() && (targetSequence === undefined || backup.replicationSequence <= targetSequence)).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()); const backup = backups[0]; if (!backup) throw new Error('No queue backup covers the requested recovery point.'); await AsyncStorage.setItem('nova.backend.worker.queue.v1', JSON.stringify(backup.queue)); await AsyncStorage.setItem('nova.backend.worker.dead-letter.v1', JSON.stringify(backup.deadLetters)); const replication = await loadReplicationState(); const restoredReplication: ReplicationState = { ...replication, lastSequence: Math.min(replication.lastSequence, backup.replicationSequence), entries: replication.entries.filter((entry) => entry.sequence <= backup.replicationSequence), regions: replication.regions.map((region) => ({ ...region, lastAppliedSequence: Math.min(region.lastAppliedSequence, backup.replicationSequence) })) }; await saveReplicationState(restoredReplication); const span = await startSpan('queue.recovery', { backupId: backup.id, targetSequence: targetSequence ?? backup.replicationSequence }, undefined, backup.sourceRegion); const started = Date.now(); await recordMetric({ name: 'recovery.duration', value: Date.now() - started, unit: 'ms', regionId: backup.sourceRegion, traceId: span.traceId }); await endSpan(span, 'ok', { restoredQueue: backup.queue.length, restoredDeadLetters: backup.deadLetters.length }); return { backupId: backup.id, restoredQueue: backup.queue.length, restoredDeadLetters: backup.deadLetters.length, targetTime, targetSequence: backup.replicationSequence, sourceRegion: backup.sourceRegion }; }
export async function pruneQueueBackups(retentionCount = 50) { const backups = await loadQueueBackups(); const retained = backups.slice(-Math.max(1, retentionCount)); await saveQueueBackups(retained); return { removed: backups.length - retained.length, retained: retained.length }; }
export async function getRecoveryReadiness() { const backups = await loadQueueBackups(); const latest = backups.at(-1); return { backupCount: backups.length, latestBackupAt: latest?.createdAt, latestSequence: latest?.replicationSequence ?? 0, coveredRegions: [...new Set(backups.flatMap((backup) => backup.targetRegions))], ready: Boolean(latest) }; }
