import AsyncStorage from '@react-native-async-storage/async-storage';
import { BackendMutation } from './contracts';
import { loadBackendStore, saveBackendStore, BackendStore } from './repository';

export type RegionStatus = 'healthy' | 'degraded' | 'unavailable' | 'promoted';
export type RegionRecord = { id: string; name: string; endpoint?: string; status: RegionStatus; priority: number; lastHeartbeatAt: string; lastAppliedSequence: number; latencyMs: number; failureCount: number };
export type ReplicationEntry = { id: string; sequence: number; originRegion: string; mutation: BackendMutation; createdAt: string; checksum: string; appliedRegions: string[] };
export type LeaderLease = { workspaceId: string; regionId: string; leaseId: string; expiresAt: string; renewedAt: string; epoch: number };
export type ReplicationState = { primaryRegion: string; regions: RegionRecord[]; entries: ReplicationEntry[]; leases: LeaderLease[]; lastSequence: number; failoverCount: number; updatedAt: string };
export type FailoverPlan = { workspaceId: string; fromRegion: string; toRegion: string; reason: string; promotedAt: string; recoveredSequence: number; dataLossWindow: number; requiresOperatorReview: boolean };
const STATE_KEY = 'nova.backend.regions.v1';
const emptyState = (): ReplicationState => ({ primaryRegion: 'us-east-1', regions: [{ id: 'us-east-1', name: 'US East', status: 'healthy', priority: 1, lastHeartbeatAt: new Date().toISOString(), lastAppliedSequence: 0, latencyMs: 0, failureCount: 0 }, { id: 'eu-west-1', name: 'EU West', status: 'healthy', priority: 2, lastHeartbeatAt: new Date().toISOString(), lastAppliedSequence: 0, latencyMs: 0, failureCount: 0 }, { id: 'ap-southeast-1', name: 'AP Southeast', status: 'healthy', priority: 3, lastHeartbeatAt: new Date().toISOString(), lastAppliedSequence: 0, latencyMs: 0, failureCount: 0 }], entries: [], leases: [], lastSequence: 0, failoverCount: 0, updatedAt: new Date().toISOString() });
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();
const checksum = (sequence: number, mutation: BackendMutation) => `${sequence}:${JSON.stringify(mutation).length}:${mutation.kind}`;
export async function loadReplicationState() { const state = parse<ReplicationState>(await AsyncStorage.getItem(STATE_KEY), emptyState()); const defaults = emptyState(); return { ...defaults, ...state, regions: state.regions?.length ? state.regions : defaults.regions, entries: state.entries ?? [], leases: state.leases ?? [] }; }
export async function saveReplicationState(state: ReplicationState) { const next = { ...state, entries: state.entries.slice(-2000), leases: state.leases.slice(-100), updatedAt: now() }; await AsyncStorage.setItem(STATE_KEY, JSON.stringify(next)); return next; }
export async function heartbeatRegion(regionId: string, latencyMs = 0, available = true) { const state = await loadReplicationState(); const region = state.regions.find((item) => item.id === regionId); if (!region) throw new Error(`Unknown region: ${regionId}`); const next = state.regions.map((item) => item.id === regionId ? { ...item, status: (available ? 'healthy' : 'unavailable') as RegionStatus, lastHeartbeatAt: now(), latencyMs, failureCount: available ? 0 : item.failureCount + 1 } : item); return saveReplicationState({ ...state, regions: next }); }
export async function appendReplicationEntry(originRegion: string, mutation: BackendMutation) { const state = await loadReplicationState(); if (!state.regions.some((item) => item.id === originRegion)) throw new Error(`Unknown origin region: ${originRegion}`); const sequence = state.lastSequence + 1; const entry: ReplicationEntry = { id: id('repl'), sequence, originRegion, mutation, createdAt: now(), checksum: checksum(sequence, mutation), appliedRegions: [originRegion] }; await saveReplicationState({ ...state, lastSequence: sequence, entries: [...state.entries, entry] }); return entry; }
export async function replicatePending(regionId: string, maxEntries = 100) { const state = await loadReplicationState(); const region = state.regions.find((item) => item.id === regionId); if (!region || region.status === 'unavailable') return { applied: [], skipped: true, reason: 'region-unavailable' }; const pending = state.entries.filter((entry) => !entry.appliedRegions.includes(regionId)).sort((a, b) => a.sequence - b.sequence).slice(0, maxEntries); const applied = pending.map((entry) => entry.id); const entries = state.entries.map((entry) => applied.includes(entry.id) ? { ...entry, appliedRegions: [...entry.appliedRegions, regionId] } : entry); const lastAppliedSequence = pending.at(-1)?.sequence ?? region.lastAppliedSequence; const regions = state.regions.map((item) => item.id === regionId ? { ...item, lastAppliedSequence, status: 'healthy' as RegionStatus, lastHeartbeatAt: now() } : item); await saveReplicationState({ ...state, entries, regions }); return { applied, skipped: false, lastAppliedSequence }; }
export async function acquireLeaderLease(workspaceId: string, regionId: string, ttlMs = 30_000) { const state = await loadReplicationState(); const current = state.leases.find((lease) => lease.workspaceId === workspaceId); const timestamp = Date.now(); if (current && new Date(current.expiresAt).getTime() > timestamp && current.regionId !== regionId) throw new Error(`Leader lease is held by ${current.regionId}.`); const lease: LeaderLease = { workspaceId, regionId, leaseId: current?.leaseId ?? id('lease'), expiresAt: new Date(timestamp + ttlMs).toISOString(), renewedAt: now(), epoch: (current?.epoch ?? 0) + (current?.regionId === regionId ? 0 : 1) }; await saveReplicationState({ ...state, leases: [...state.leases.filter((item) => item.workspaceId !== workspaceId), lease] }); return lease; }
export async function releaseLeaderLease(workspaceId: string, regionId: string) { const state = await loadReplicationState(); await saveReplicationState({ ...state, leases: state.leases.filter((lease) => !(lease.workspaceId === workspaceId && lease.regionId === regionId)) }); }
export async function planFailover(workspaceId: string, reason: string, forcedRegion?: string): Promise<FailoverPlan> { const state = await loadReplicationState(); const primary = state.regions.find((region) => region.id === state.primaryRegion); if (!primary) throw new Error('Primary region is not configured.'); const candidates = state.regions.filter((region) => region.id !== state.primaryRegion && region.status !== 'unavailable').sort((a, b) => a.priority - b.priority || a.lastAppliedSequence - b.lastAppliedSequence); const target = candidates.find((region) => region.id === forcedRegion) ?? candidates[0]; if (!target) throw new Error('No healthy failover region is available.'); return { workspaceId, fromRegion: state.primaryRegion, toRegion: target.id, reason, promotedAt: now(), recoveredSequence: target.lastAppliedSequence, dataLossWindow: Math.max(0, state.lastSequence - target.lastAppliedSequence), requiresOperatorReview: state.lastSequence !== target.lastAppliedSequence }; }
export async function executeFailover(plan: FailoverPlan) { const state = await loadReplicationState(); const target = state.regions.find((region) => region.id === plan.toRegion); if (!target) throw new Error('Failover target disappeared.'); const nextRegions = state.regions.map((region) => region.id === plan.fromRegion ? { ...region, status: 'degraded' as RegionStatus } : region.id === plan.toRegion ? { ...region, status: 'promoted' as RegionStatus, lastHeartbeatAt: now() } : region); const next = await saveReplicationState({ ...state, primaryRegion: plan.toRegion, regions: nextRegions, failoverCount: state.failoverCount + 1, leases: state.leases.filter((lease) => lease.workspaceId !== plan.workspaceId) }); const lease = await acquireLeaderLease(plan.workspaceId, plan.toRegion, 30_000); return { plan, state: next, lease }; }
export async function exportReplicationSnapshot() { const state = await loadReplicationState(); const store = await loadBackendStore(); return { generatedAt: now(), region: state.primaryRegion, sequence: state.lastSequence, store, replication: state }; }
export async function importReplicationSnapshot(snapshot: { store: BackendStore; replication: ReplicationState }) { await saveBackendStore(snapshot.store); return saveReplicationState(snapshot.replication); }
