import AsyncStorage from '@react-native-async-storage/async-storage';
import { AuditRecord, ConnectorRecord, NotificationRecord, ProjectRecord, ServerSnapshot, TaskRecord, UsageMetric, WorkflowRecord } from './domain';

export type BackendStore = { projects: ProjectRecord[]; tasks: TaskRecord[]; workflows: WorkflowRecord[]; connectors: ConnectorRecord[]; audit: AuditRecord[]; usage: UsageMetric[]; notifications: NotificationRecord[] };
const STORE_KEY = 'nova.backend.domain-store.v1';
const emptyStore: BackendStore = { projects: [], tasks: [], workflows: [], connectors: [], audit: [], usage: [], notifications: [] };
const parse = <T,>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();

export async function loadBackendStore() { return { ...emptyStore, ...parse<Partial<BackendStore>>(await AsyncStorage.getItem(STORE_KEY), {}) }; }
export async function saveBackendStore(store: BackendStore) { await AsyncStorage.setItem(STORE_KEY, JSON.stringify(store)); return store; }
export async function resetBackendStore() { await saveBackendStore(emptyStore); return emptyStore; }
export async function createProject(input: Pick<ProjectRecord, 'workspaceId' | 'name' | 'description' | 'color' | 'ownerId'>) { const store = await loadBackendStore(); const project: ProjectRecord = { ...input, id: id('project'), status: 'active', tags: [], createdAt: now(), updatedAt: now() }; store.projects = [project, ...store.projects]; await saveBackendStore(store); return project; }
export async function updateProject(idValue: string, patch: Partial<ProjectRecord>) { const store = await loadBackendStore(); store.projects = store.projects.map((item) => item.id === idValue ? { ...item, ...patch, updatedAt: now() } : item); await saveBackendStore(store); return store.projects.find((item) => item.id === idValue); }
export async function createTask(input: Pick<TaskRecord, 'projectId' | 'title' | 'description' | 'priority'>) { const store = await loadBackendStore(); const task: TaskRecord = { ...input, id: id('task'), status: 'todo', labels: [], createdAt: now(), updatedAt: now() }; store.tasks = [task, ...store.tasks]; await saveBackendStore(store); return task; }
export async function updateTask(idValue: string, patch: Partial<TaskRecord>) { const store = await loadBackendStore(); store.tasks = store.tasks.map((item) => item.id === idValue ? { ...item, ...patch, updatedAt: now() } : item); await saveBackendStore(store); return store.tasks.find((item) => item.id === idValue); }
export async function createWorkflow(input: Pick<WorkflowRecord, 'workspaceId' | 'name' | 'description' | 'trigger' | 'steps'>) { const store = await loadBackendStore(); const workflow: WorkflowRecord = { ...input, id: id('workflow'), enabled: true, createdAt: now(), updatedAt: now() }; store.workflows = [workflow, ...store.workflows]; await saveBackendStore(store); return workflow; }
export async function toggleWorkflow(idValue: string) { const store = await loadBackendStore(); store.workflows = store.workflows.map((item) => item.id === idValue ? { ...item, enabled: !item.enabled, updatedAt: now() } : item); await saveBackendStore(store); return store.workflows.find((item) => item.id === idValue); }
export async function upsertConnector(input: Omit<ConnectorRecord, 'id' | 'createdAt' | 'updatedAt'> & { id?: string }) { const store = await loadBackendStore(); const timestamp = now(); const connector: ConnectorRecord = { ...input, id: input.id ?? id('connector'), createdAt: timestamp, updatedAt: timestamp }; store.connectors = [connector, ...store.connectors.filter((item) => item.id !== connector.id)]; await saveBackendStore(store); return connector; }
export async function appendAudit(input: Omit<AuditRecord, 'id' | 'createdAt'>) { const store = await loadBackendStore(); const record: AuditRecord = { ...input, id: id('audit'), createdAt: now() }; store.audit = [record, ...store.audit].slice(0, 1000); await saveBackendStore(store); return record; }
export async function recordUsage(input: Omit<UsageMetric, 'id' | 'createdAt'>) { const store = await loadBackendStore(); const metric: UsageMetric = { ...input, id: id('usage'), createdAt: now() }; store.usage = [metric, ...store.usage].slice(0, 365); await saveBackendStore(store); return metric; }
export async function queueNotification(input: Omit<NotificationRecord, 'id' | 'createdAt' | 'status'>) { const store = await loadBackendStore(); const notification: NotificationRecord = { ...input, id: id('notification'), status: 'queued', createdAt: now() }; store.notifications = [notification, ...store.notifications]; await saveBackendStore(store); return notification; }
export async function getServerSnapshot(workspaceId: string): Promise<ServerSnapshot> { const store = await loadBackendStore(); return { version: 1, workspaceId, ...store, cursor: `${Date.now()}`, generatedAt: now() }; }
