import { appendAudit, createProject, createTask, createWorkflow, getServerSnapshot, loadBackendStore, queueNotification, recordUsage, toggleWorkflow, updateTask, upsertConnector } from './repository';
import { ConnectorRecord, ProjectRecord, TaskRecord, WorkflowRecord } from './domain';
import { BackendClient, enqueueMutation, loadBackendConfig } from './client';

export async function bootstrapWorkspace(workspaceId: string, ownerId = 'local-user') { const store = await loadBackendStore(); if (!store.projects.length) await createProject({ workspaceId, ownerId, name: 'Nova Command Center', description: 'A structured workspace for local and remote operations.', color: '#55d6ff' }); if (!store.connectors.length) { await upsertConnector({ workspaceId, provider: 'webhook', name: 'Inbound events', status: 'not_configured' }); await upsertConnector({ workspaceId, provider: 'analytics', name: 'Usage metrics', status: 'connected' }); } return getServerSnapshot(workspaceId); }
export async function createProjectPlan(workspaceId: string, ownerId: string, name: string, description: string) { const project = await createProject({ workspaceId, ownerId, name, description, color: '#a78bfa' }); const firstTasks = ['Define outcome', 'Map milestones', 'Identify risks', 'Choose first action']; const tasks = await Promise.all(firstTasks.map((title, index) => createTask({ projectId: project.id, title, description: `${title} for ${name}`, priority: index === 0 ? 'high' : 'medium' }))); await appendAudit({ workspaceId, actorId: ownerId, action: 'project.created_with_plan', resource: 'project', resourceId: project.id, risk: 'low', metadata: { taskCount: tasks.length } }); await recordUsage({ workspaceId, day: new Date().toISOString().slice(0, 10), runs: 1, toolCalls: 1, filesIndexed: 0, syncs: 0, errors: 0, latencyMs: 0 }); return { project, tasks }; }
export async function triageTask(taskId: string, decision: TaskRecord['status'], actorId: string, workspaceId: string) { const task = await updateTask(taskId, { status: decision }); await appendAudit({ workspaceId, actorId, action: 'task.triaged', resource: 'task', resourceId: taskId, risk: decision === 'blocked' ? 'medium' : 'low', metadata: { decision } }); return task; }
export async function createDefaultWorkflow(workspaceId: string) { return createWorkflow({ workspaceId, name: 'File to task pipeline', description: 'Index an imported file, create a review task, and notify the workspace.', trigger: 'file_import', steps: [{ id: 'index', type: 'tool', name: 'Index metadata', config: { toolId: 'file-index' }, risk: 'safe' }, { id: 'review', type: 'approval', name: 'Request review', config: {}, risk: 'review' }, { id: 'notify', type: 'notification', name: 'Notify workspace', config: { channel: 'local' }, risk: 'safe' }] }); }
export async function runWorkflow(workflowId: string, workspaceId: string, actorId: string) { const store = await loadBackendStore(); const workflow = store.workflows.find((item) => item.id === workflowId); if (!workflow) throw new Error('Workflow not found.'); if (!workflow.enabled) throw new Error('Workflow is disabled.'); await appendAudit({ workspaceId, actorId, action: 'workflow.executed', resource: 'workflow', resourceId: workflowId, risk: workflow.steps.some((step) => step.risk === 'sensitive') ? 'high' : 'low', metadata: { stepCount: workflow.steps.length } }); await queueNotification({ workspaceId, channel: 'local', title: 'Workflow completed', body: `${workflow.name} completed ${workflow.steps.length} steps.`, route: '/jobs' }); return workflow; }
export async function checkConnectors(workspaceId: string) { const store = await loadBackendStore(); const config = await loadBackendConfig(); const client = new BackendClient(config); const remote = await client.health(); const updated: ConnectorRecord[] = []; for (const connector of store.connectors) { const status = connector.provider === 'webhook' ? connector.status : remote.status === 'healthy' ? 'connected' : 'error'; updated.push(await upsertConnector({ ...connector, status, lastCheckedAt: new Date().toISOString() })); } return { remote, connectors: updated }; }
export async function dispatchOrQueueRemoteTool(toolId: string, input: Record<string, unknown>) { const config = await loadBackendConfig(); const client = new BackendClient(config); if (!client.enabled) return enqueueMutation('job', { toolId, input }, 'Remote backend is offline.'); try { return await client.dispatchTool(toolId, input); } catch (error) { return enqueueMutation('job', { toolId, input }, error instanceof Error ? error.message : 'Remote dispatch failed.'); } }
export async function aggregateUsage(workspaceId: string) { const store = await loadBackendStore(); const relevant = store.usage.filter((item) => item.workspaceId === workspaceId); return { runs: relevant.reduce((sum, item) => sum + item.runs, 0), toolCalls: relevant.reduce((sum, item) => sum + item.toolCalls, 0), filesIndexed: relevant.reduce((sum, item) => sum + item.filesIndexed, 0), syncs: relevant.reduce((sum, item) => sum + item.syncs, 0), errors: relevant.reduce((sum, item) => sum + item.errors, 0), avgLatencyMs: relevant.length ? Math.round(relevant.reduce((sum, item) => sum + item.latencyMs, 0) / relevant.length) : 0 }; }
export { toggleWorkflow };
export type { ProjectRecord, TaskRecord, WorkflowRecord };
