export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  providerOrder: process.env.NOVA_PROVIDER_ORDER ?? "gemini,groq,ollama-cloud,openrouter",
  geminiApiKeys: process.env.GEMINI_API_KEYS ?? process.env.GEMINI_API_KEY ?? "",
  groqApiKeys: process.env.GROQ_API_KEYS ?? process.env.GROQ_API_KEY ?? "",
  ollamaCloudApiKeys: process.env.OLLAMA_CLOUD_API_KEYS ?? process.env.OLLAMA_CLOUD_API_KEY ?? "",
  openrouterApiKeys: process.env.OPENROUTER_API_KEYS ?? process.env.OPENROUTER_API_KEY ?? "",
  kaggleApiKeys: process.env.KAGGLE_API_KEYS ?? process.env.KAGGLE_API_KEY ?? "",
  firecrawlApiKeys: process.env.FIRECRAWL_API_KEYS ?? process.env.FIRECRAWL_API_KEY ?? "",
  e2bApiKeys: process.env.E2B_API_KEYS ?? process.env.E2B_API_KEY ?? "",
};
