export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  oauthPortalUrl: process.env.VITE_OAUTH_PORTAL_URL ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  providerOrder: process.env.NOVA_PROVIDER_ORDER ?? "gemini,groq,ollama-cloud,openrouter",
  geminiApiKeys: process.env.GEMINI_API_KEYS ?? process.env.GEMINI_API_KEY ?? "",
  groqApiKeys: process.env.GROQ_API_KEYS ?? process.env.GROQ_API_KEY ?? "",
  ollamaCloudApiKeys: process.env.OLLAMA_CLOUD_API_KEYS ?? process.env.OLLAMA_CLOUD_API_KEY ?? "",
  openrouterApiKeys: process.env.OPENROUTER_API_KEYS ?? process.env.OPENROUTER_API_KEY ?? "",
  geminiModel: process.env.GEMINI_MODEL ?? "gemini-2.5-flash",
  groqModel: process.env.GROQ_MODEL ?? "llama-3.3-70b-versatile",
  ollamaCloudModel: process.env.OLLAMA_CLOUD_MODEL ?? "llama3.2",
  ollamaCloudBaseUrl: process.env.OLLAMA_CLOUD_BASE_URL ?? "https://ollama.com/v1",
  openrouterModel: process.env.OPENROUTER_MODEL ?? "openai/gpt-4o-mini",
  openrouterBaseUrl: process.env.OPENROUTER_BASE_URL ?? "https://openrouter.ai/api/v1",
  kaggleApiKeys: process.env.KAGGLE_API_KEYS ?? process.env.KAGGLE_API_KEY ?? "",
  firecrawlApiKeys: process.env.FIRECRAWL_API_KEYS ?? process.env.FIRECRAWL_API_KEY ?? "",
  e2bApiKeys: process.env.E2B_API_KEYS ?? process.env.E2B_API_KEY ?? "",
  cloudflareWorkerUrl: process.env.CLOUDFLARE_WORKER_URL ?? "",
  cloudflareWorkerToken: process.env.CLOUDFLARE_WORKER_TOKEN ?? "",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  massiveWsUrl: process.env.MASSIVE_WS_URL ?? "",
  massiveApiKey: process.env.MASSIVE_API_KEY ?? "",
  passwordHash: process.env.NOVA_ACCESS_PASSWORD_HASH ?? "",
};
