import { ENV } from "./env";

export type MarketStreamProvider = "coinbase" | "massive";
export type MarketStreamAsset = "crypto" | "stock";
export type NormalizedMarketEvent = { provider: MarketStreamProvider; asset: MarketStreamAsset; symbol: string; event: "trade" | "quote" | "bar" | "status" | "unknown"; price?: number; size?: number; bid?: number; ask?: number; timestamp?: number; sequence?: number; rawType?: string };

const coinbaseUrl = "wss://advanced-trade-ws.coinbase.com";

export function listMarketStreams() { return [
  { provider: "coinbase" as const, assets: ["crypto" as const], url: coinbaseUrl, authRequired: false, channels: ["ticker", "market_trades", "level2", "candles"], configured: true, note: "Public market-data channels; keep keys server-side if authenticated channels are enabled." },
  { provider: "massive" as const, assets: ["stock" as const, "crypto" as const], url: ENV.massiveWsUrl || null, authRequired: true, channels: ["trades", "quotes", "bars"], configured: Boolean(ENV.massiveWsUrl && ENV.massiveApiKey), note: "Configure MASSIVE_WS_URL and MASSIVE_API_KEY server-side; never expose the key to browsers." },
]; }

export function buildCoinbaseSubscription(productIds: string[], channel: "ticker" | "market_trades" | "level2" | "candles" = "ticker") { const products = productIds.map(String).filter(Boolean).slice(0, 50); if (!products.length) throw new Error("At least one product is required"); return { type: "subscribe", channel, product_ids: products }; }
export function buildMassiveSubscription(symbols: string[], channel: "trades" | "quotes" | "bars" = "trades") { const safe = symbols.map(symbol => String(symbol).trim().toUpperCase()).filter(Boolean).slice(0, 100); if (!safe.length) throw new Error("At least one symbol is required"); return { action: "subscribe", params: `${channel}:${safe.join(",")}` }; }

export function normalizeMarketEvent(provider: MarketStreamProvider, payload: unknown, asset: MarketStreamAsset): NormalizedMarketEvent[] { if (!payload || typeof payload !== "object") return []; const root = payload as Record<string, unknown>; const rows = Array.isArray(root.events) ? root.events : Array.isArray(payload) ? payload : [payload]; return rows.flatMap(row => { if (!row || typeof row !== "object") return []; const item = row as Record<string, unknown>; const symbol = String(item.product_id ?? item.sym ?? item.symbol ?? item.p ?? "UNKNOWN"); const price = Number(item.price ?? item.px ?? item.c ?? item.close); const size = Number(item.size ?? item.s ?? item.q ?? item.volume); const bid = Number(item.best_bid ?? item.bid_price ?? item.bp); const ask = Number(item.best_ask ?? item.ask_price ?? item.ap); const timestampRaw = item.time ?? item.timestamp ?? item.t ?? item.start; const timestamp = timestampRaw ? new Date(String(timestampRaw)).getTime() || Number(timestampRaw) : undefined; const type = String(item.type ?? item.ev ?? item.channel ?? "unknown"); const event: NormalizedMarketEvent["event"] = /trade/i.test(type) ? "trade" : /quote|level2/i.test(type) ? "quote" : /bar|candle|agg/i.test(type) ? "bar" : /status|subscriptions/i.test(type) ? "status" : "unknown"; return [{ provider, asset, symbol, event, price: Number.isFinite(price) ? price : undefined, size: Number.isFinite(size) ? size : undefined, bid: Number.isFinite(bid) ? bid : undefined, ask: Number.isFinite(ask) ? ask : undefined, timestamp: Number.isFinite(timestamp) ? timestamp : undefined, sequence: Number.isFinite(Number(item.sequence_num ?? item.seq)) ? Number(item.sequence_num ?? item.seq) : undefined, rawType: type }]; }); }

export function detectSequenceGap(previous: number | undefined, current: number | undefined) { if (previous === undefined || current === undefined) return { gap: false, expected: undefined, received: current }; return { gap: current > previous + 1, expected: previous + 1, received: current }; }
