export type NoteEvent = { note: number; start: number; duration: number; velocity: number };

const SCALE_INTERVALS: Record<string, number[]> = { major: [0, 2, 4, 5, 7, 9, 11], minor: [0, 2, 3, 5, 7, 8, 10], dorian: [0, 2, 3, 5, 7, 9, 10], pentatonic: [0, 2, 4, 7, 9], blues: [0, 3, 5, 6, 7, 10] };

export function scaleNotes(root = 60, scale = "major", octaves = 2) { const intervals = SCALE_INTERVALS[scale] ?? SCALE_INTERVALS.major; return Array.from({ length: Math.max(1, octaves) }, (_, octave) => intervals.map(interval => root + octave * 12 + interval)).flat(); }
export function chordExtensions(root: number, quality: "major" | "minor" | "dominant" | "diminished" = "major", extensions: number[] = [7, 9]) { const base = quality === "minor" ? [0, 3, 7] : quality === "dominant" ? [0, 4, 7, 10] : quality === "diminished" ? [0, 3, 6] : [0, 4, 7]; const extra = extensions.map(extension => extension === 7 ? (quality === "major" ? 11 : 10) : extension === 9 ? 14 : extension === 11 ? 17 : 21); return [...base, ...extra].map(interval => root + interval); }
export function quantizeNotes(events: NoteEvent[], grid = 0.25, strength = 1) { const safeGrid = Math.max(0.001, grid); return events.map(event => ({ ...event, start: event.start + (Math.round(event.start / safeGrid) * safeGrid - event.start) * Math.max(0, Math.min(1, strength)) })); }
export function euclideanRhythm(steps: number, pulses: number, rotation = 0) { const n = Math.max(1, Math.floor(steps)); const k = Math.max(0, Math.min(n, Math.floor(pulses))); const pattern = Array.from({ length: n }, (_, i) => Math.floor((i * k) / n) !== Math.floor(((i - 1 + n) % n) * k / n)); const shift = ((rotation % n) + n) % n; return pattern.map((_, i) => pattern[(i - shift + n) % n]); }
export function drumGrid(steps = 16, density = 0.5, seed = 7) { const safeSteps = Math.max(1, Math.min(128, Math.floor(steps))); let state = Math.abs(seed) || 7; const next = () => { state = (state * 1664525 + 1013904223) >>> 0; return state / 4294967296; }; return { kick: Array.from({ length: safeSteps }, (_, i) => i % 4 === 0 || next() < density * 0.12), snare: Array.from({ length: safeSteps }, (_, i) => i % 8 === 4 || next() < density * 0.05), hat: Array.from({ length: safeSteps }, () => next() < Math.min(0.98, density + 0.25)) }; }
export function shapeAutomation(points: number[], curve: "linear" | "ease-in" | "ease-out" | "sine" = "linear", samples = points.length) { const source = points.length ? points : [0, 1]; const count = Math.max(2, samples); const at = (t: number) => { const scaled = t * (source.length - 1); const left = Math.floor(scaled); const right = Math.min(source.length - 1, left + 1); const local = scaled - left; let eased = local; if (curve === "ease-in") eased = local * local; if (curve === "ease-out") eased = 1 - (1 - local) * (1 - local); if (curve === "sine") eased = (1 - Math.cos(local * Math.PI)) / 2; return source[left] + (source[right] - source[left]) * eased; }; return Array.from({ length: count }, (_, i) => at(i / (count - 1))); }
export function chordProgression(root = 60, quality: "major" | "minor" = "major", degrees: number[] = [1, 5, 6, 4]) { const scale = scaleNotes(root, quality === "minor" ? "minor" : "major", 3); return degrees.map(degree => scale[Math.max(0, degree - 1)] ?? root).map(note => [note, note + (quality === "minor" ? 3 : 4), note + 7]); }
export function arpeggiate(notes: number[], pattern: "up" | "down" | "updown" = "up", octaves = 1) { const source = notes.length ? notes : [60, 64, 67]; const order = pattern === "down" ? [...source].reverse() : pattern === "updown" ? [...source, ...source.slice(1, -1).reverse()] : source; return Array.from({ length: Math.max(1, octaves) }, (_, octave) => order.map(note => note + octave * 12)).flat(); }
export function swingQuantize(events: NoteEvent[], grid = 0.25, swing = 0.5) { const safeSwing = Math.max(0, Math.min(.99, swing)); return events.map(event => { const slot = Math.round(event.start / Math.max(.001, grid)); const offset = slot % 2 ? grid * (safeSwing - .5) : 0; return { ...event, start: Math.max(0, slot * grid + offset) }; }); }
export function humanizeNotes(events: NoteEvent[], timing = .01, velocity = 5, seed = 17) { let state = Math.abs(seed) || 17; const next = () => { state = (state * 1664525 + 1013904223) >>> 0; return state / 4294967296 - .5; }; return events.map(event => ({ ...event, start: Math.max(0, event.start + next() * timing), velocity: Math.max(1, Math.min(127, Math.round(event.velocity + next() * velocity))) })); }
export function velocityCurve(events: NoteEvent[], curve: "linear" | "ease-in" | "ease-out" = "linear") { if (!events.length) return []; const max = Math.max(...events.map(e => e.velocity), 1); return events.map((event, i) => { const t = events.length === 1 ? 1 : i / (events.length - 1); const shaped = curve === "ease-in" ? t * t : curve === "ease-out" ? 1 - (1 - t) ** 2 : t; return { ...event, velocity: Math.max(1, Math.min(127, Math.round(event.velocity * .5 + max * shaped * .5))) }; }); }
export function midiNoteName(note: number) { const names = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]; const safe = Math.round(note); return `${names[((safe % 12) + 12) % 12]}${Math.floor(safe / 12) - 1}`; }
