import type { AdvancedCandle } from "./technicalAdvanced";

const closes = (data: AdvancedCandle[]) => data.map(c => c.close);
const avg = (values: number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
const trueRange = (data: AdvancedCandle[]) => data.map((c, i) => i === 0 ? c.high - c.low : Math.max(c.high - c.low, Math.abs(c.high - data[i - 1].close), Math.abs(c.low - data[i - 1].close)));
const sma = (values: number[], period: number) => values.slice(-Math.max(1, period)).reduce((a, b) => a + b, 0) / Math.max(1, Math.min(period, values.length));
const ema = (values: number[], period: number) => { if (!values.length) return 0; const k = 2 / (period + 1); let result = values[0]; for (const value of values.slice(1)) result = value * k + result * (1 - k); return result; };
const stdev = (values: number[]) => { const mean = avg(values); return Math.sqrt(avg(values.map(v => (v - mean) ** 2))); };
const pct = (a: number, b: number) => b === 0 ? 0 : (a - b) / b * 100;

export function smaIndicator(data: AdvancedCandle[], period = 20) { return { period, value: sma(closes(data), period) }; }
export function emaIndicator(data: AdvancedCandle[], period = 20) { return { period, value: ema(closes(data), period) }; }
export function wmaIndicator(data: AdvancedCandle[], period = 20) { const values = closes(data).slice(-period); const denom = values.length * (values.length + 1) / 2 || 1; return { period, value: values.reduce((sum, value, i) => sum + value * (i + 1), 0) / denom }; }
export function hmaIndicator(data: AdvancedCandle[], period = 20) { const half = Math.max(2, Math.floor(period / 2)); const wmaHalf = wmaIndicator(data, half).value; const wmaFull = wmaIndicator(data, period).value; return { period, value: 2 * wmaHalf - wmaFull }; }
export function macdIndicator(data: AdvancedCandle[], fast = 12, slow = 26, signal = 9) { const values = closes(data); const macd = ema(values, fast) - ema(values, slow); return { fast, slow, signal, macd, signalLine: ema(values.slice(-signal).map((_, i, a) => ema(values.slice(0, values.length - signal + i + 1), fast) - ema(values.slice(0, values.length - signal + i + 1), slow)), signal), histogram: macd - ema(values.slice(-signal).map((_, i, a) => ema(values.slice(0, values.length - signal + i + 1), fast) - ema(values.slice(0, values.length - signal + i + 1), slow)), signal) }; }
export function stochasticIndicator(data: AdvancedCandle[], period = 14, smooth = 3) { const sample = data.slice(-period); const high = Math.max(...sample.map(c => c.high), 0); const low = Math.min(...sample.map(c => c.low), 0); const close = sample.at(-1)?.close ?? 0; const k = high === low ? 50 : (close - low) / (high - low) * 100; return { period, smooth, k, d: k }; }
export function atrIndicator(data: AdvancedCandle[], period = 14) { return { period, value: sma(trueRange(data), period) }; }
export function bollingerIndicator(data: AdvancedCandle[], period = 20, multiplier = 2) { const values = closes(data).slice(-period); const middle = avg(values); const deviation = stdev(values); return { period, multiplier, middle, upper: middle + multiplier * deviation, lower: middle - multiplier * deviation, bandwidth: middle === 0 ? 0 : (2 * multiplier * deviation) / middle * 100 }; }
export function keltnerIndicator(data: AdvancedCandle[], period = 20, multiplier = 2) { const middle = ema(closes(data), period); const atr = atrIndicator(data, Math.min(period, 14)).value; return { period, multiplier, middle, upper: middle + multiplier * atr, lower: middle - multiplier * atr }; }
export function donchianIndicator(data: AdvancedCandle[], period = 20) { const sample = data.slice(-period); return { period, upper: Math.max(...sample.map(c => c.high), 0), lower: Math.min(...sample.map(c => c.low), 0), middle: avg([Math.max(...sample.map(c => c.high), 0), Math.min(...sample.map(c => c.low), 0)]) }; }
export function rocIndicator(data: AdvancedCandle[], period = 12) { const values = closes(data); return { period, value: pct(values.at(-1) ?? 0, values[Math.max(0, values.length - 1 - period)] ?? 0) }; }
export function momentumIndicator(data: AdvancedCandle[], period = 10) { const values = closes(data); return { period, value: (values.at(-1) ?? 0) - (values[Math.max(0, values.length - 1 - period)] ?? 0) }; }
export function mfiIndicator(data: AdvancedCandle[], period = 14) { const sample = data.slice(-(period + 1)); let positive = 0; let negative = 0; sample.slice(1).forEach((c, i) => { const prev = sample[i]; const flow = ((c.high + c.low + c.close) / 3) * c.volume; if (c.close >= prev.close) positive += flow; else negative += flow; }); const ratio = negative === 0 ? 100 : positive / negative; return { period, value: 100 - 100 / (1 + ratio) }; }
export function obvIndicator(data: AdvancedCandle[]) { let value = 0; data.slice(1).forEach((c, i) => { if (c.close > data[i].close) value += c.volume; else if (c.close < data[i].close) value -= c.volume; }); return { value }; }
export function vwapIndicator(data: AdvancedCandle[]) { let pv = 0; let volume = 0; for (const c of data) { pv += ((c.high + c.low + c.close) / 3) * c.volume; volume += c.volume; } return { value: volume ? pv / volume : 0 }; }
export function adxIndicator(data: AdvancedCandle[], period = 14) { const trs = trueRange(data); const plus: number[] = []; const minus: number[] = []; for (let i = 1; i < data.length; i++) { const up = data[i].high - data[i - 1].high; const down = data[i - 1].low - data[i].low; plus.push(up > down && up > 0 ? up : 0); minus.push(down > up && down > 0 ? down : 0); } const atr = sma(trs, period) || 1; const pdi = sma(plus, period) / atr * 100; const mdi = sma(minus, period) / atr * 100; return { period, plusDI: pdi, minusDI: mdi, adx: (pdi + mdi) === 0 ? 0 : Math.abs(pdi - mdi) / (pdi + mdi) * 100 }; }
export function cmoIndicator(data: AdvancedCandle[], period = 14) { const changes = closes(data).slice(1).map((v, i) => v - closes(data)[i]).slice(-period); const up = changes.filter(v => v > 0).reduce((a, b) => a + b, 0); const down = Math.abs(changes.filter(v => v < 0).reduce((a, b) => a + b, 0)); return { period, value: up + down === 0 ? 0 : (up - down) / (up + down) * 100 }; }
export function ulcerIndexIndicator(data: AdvancedCandle[], period = 14) { const sample = closes(data).slice(-period); const max = Math.max(...sample, 0); const squared = sample.map(v => ((v - max) / (max || 1) * 100) ** 2); return { period, value: Math.sqrt(avg(squared)) }; }
export function zScoreIndicator(data: AdvancedCandle[], period = 20) { const sample = closes(data).slice(-period); const mean = avg(sample); const deviation = stdev(sample); return { period, value: deviation === 0 ? 0 : ((sample.at(-1) ?? 0) - mean) / deviation }; }
export function realizedVolatilityIndicator(data: AdvancedCandle[], period = 20) { const values = closes(data).slice(-period); const returns = values.slice(1).map((v, i) => Math.log(v / (values[i] || v))); return { period, value: stdev(returns) * Math.sqrt(252) * 100 }; }
export function heikinAshiIndicator(data: AdvancedCandle[]) { let previousOpen = data[0]?.open ?? 0; let previousClose = data[0]?.close ?? 0; const result = data.map(c => { const close = (c.open + c.high + c.low + c.close) / 4; const open = (previousOpen + previousClose) / 2; previousOpen = open; previousClose = close; return { open, high: Math.max(c.high, open, close), low: Math.min(c.low, open, close), close }; }); return result.at(-1) ?? { open: 0, high: 0, low: 0, close: 0 }; }
export function pivotRangeIndicator(data: AdvancedCandle[]) { const c = data.at(-1); if (!c) return { top: 0, bottom: 0, width: 0 }; const pivot = (c.high + c.low + c.close) / 3; const bottom = (c.high + c.low) / 2; const top = 2 * pivot - bottom; return { top, bottom, width: top - bottom }; }
export function indicatorSuite(data: AdvancedCandle[], requested?: string[]) { const names = requested?.length ? requested : ["sma", "ema", "macd", "rsi", "bollinger", "atr", "adx", "stochastic", "vwap", "obv", "mfi", "donchian", "roc", "zscore", "volatility"]; const output: Record<string, unknown> = {}; for (const name of names) { switch (name) { case "sma": output.sma = smaIndicator(data); break; case "ema": output.ema = emaIndicator(data); break; case "wma": output.wma = wmaIndicator(data); break; case "hma": output.hma = hmaIndicator(data); break; case "macd": output.macd = macdIndicator(data); break; case "rsi": output.rsi = rsiValue(data); break; case "bollinger": output.bollinger = bollingerIndicator(data); break; case "keltner": output.keltner = keltnerIndicator(data); break; case "donchian": output.donchian = donchianIndicator(data); break; case "stochastic": output.stochastic = stochasticIndicator(data); break; case "atr": output.atr = atrIndicator(data); break; case "adx": output.adx = adxIndicator(data); break; case "mfi": output.mfi = mfiIndicator(data); break; case "obv": output.obv = obvIndicator(data); break; case "vwap": output.vwap = vwapIndicator(data); break; case "roc": output.roc = rocIndicator(data); break; case "momentum": output.momentum = momentumIndicator(data); break; case "cmo": output.cmo = cmoIndicator(data); break; case "ulcer": output.ulcer = ulcerIndexIndicator(data); break; case "zscore": output.zscore = zScoreIndicator(data); break; case "volatility": output.volatility = realizedVolatilityIndicator(data); break; case "heikinAshi": output.heikinAshi = heikinAshiIndicator(data); break; case "pivotRange": output.pivotRange = pivotRangeIndicator(data); break; default: output[name] = { error: "Unknown indicator" }; } } return output; }
function rsiValue(data: AdvancedCandle[], period = 14) { const values = closes(data); const changes = values.slice(1).map((v, i) => v - values[i]); const recent = changes.slice(-period); const gains = avg(recent.map(v => Math.max(v, 0))); const losses = avg(recent.map(v => Math.max(-v, 0))); return { period, value: losses === 0 ? 100 : 100 - 100 / (1 + gains / losses) }; }
