import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useDomain } from '../src/backend/DomainProvider';
import { colors, radii } from '../src/ui/theme';
export default function Analytics(){const {summary,usage,refresh}=useDomain();return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / INSIGHTS</Text><Text style={s.title}>Analytics</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View><Text style={s.subtitle}>Local usage metrics make the backend observable without sending telemetry unless you enable it.</Text><View style={s.grid}><Metric label="Runs" value={summary.runs}/><Metric label="Tool calls" value={summary.toolCalls}/><Metric label="Files indexed" value={summary.filesIndexed}/><Metric label="Syncs" value={summary.syncs}/><Metric label="Errors" value={summary.errors}/><Metric label="Avg latency" value={`${summary.avgLatencyMs}ms`}/></View><Text style={s.section}>Daily rollups</Text>{usage.slice(0,14).map(metric=><View key={metric.id} style={s.row}><Text style={s.day}>{metric.day}</Text><Text style={s.value}>{metric.runs} runs</Text><Text style={s.value}>{metric.toolCalls} calls</Text><Text style={s.error}>{metric.errors} errors</Text></View>)}{usage.length===0&&<Text style={s.empty}>No usage rollups yet. Run a plan, process a job, or create a workflow.</Text>}<Pressable style={s.refresh} onPress={()=>void refresh()}><Ionicons name="refresh-outline" color={colors.primary} size={18}/><Text style={s.refreshText}>Refresh metrics</Text></Pressable></ScrollView></SafeAreaView>}
function Metric({label,value}:{label:string;value:number|string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{width:'31%',minWidth:90,padding:12,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},metricValue:{color:colors.primary,fontWeight:'900',fontSize:20},metricLabel:{color:colors.muted,fontSize:11,marginTop:4},section:{color:colors.muted,textTransform:'uppercase',fontSize:11,letterSpacing:1.4,fontWeight:'800',marginTop:8},row:{padding:13,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',gap:10,alignItems:'center'},day:{color:colors.text,fontWeight:'800',flex:1},value:{color:colors.muted,fontSize:11},error:{color:colors.purple,fontSize:11},empty:{color:colors.muted,lineHeight:22},refresh:{padding:13,borderRadius:11,borderWidth:1,borderColor:colors.border,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7},refreshText:{color:colors.primary,fontWeight:'800'}});
