import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { loadBackendStore } from '../src/backend/repository';
import { AuditRecord } from '../src/backend/domain';
import { colors, radii } from '../src/ui/theme';
import { useEffect, useState } from 'react';
export default function Audit(){const [items,setItems]=useState<AuditRecord[]>([]);const [filter,setFilter]=useState<'all'|'low'|'medium'|'high'>('all');const refresh=async()=>setItems((await loadBackendStore()).audit);useEffect(()=>{void refresh()},[]);const visible=filter==='all'?items:items.filter(item=>item.risk===filter);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / GOVERNANCE</Text><Text style={s.title}>Audit Explorer</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View><Text style={s.subtitle}>Every sensitive workflow, task triage, connector operation, and automation run leaves a local record.</Text><View style={s.filters}>{(['all','low','medium','high'] as const).map(value=><Pressable key={value} style={[s.filter,filter===value&&s.active]} onPress={()=>setFilter(value)}><Text style={[s.filterText,filter===value&&s.activeText]}>{value}</Text></Pressable>)}</View><Text style={s.meta}>{visible.length} records</Text>{visible.map(item=><View key={item.id} style={s.card}><View style={s.top}><View style={s.copy}><Text style={s.action}>{item.action}</Text><Text style={s.meta}>{item.resource}{item.resourceId?` · ${item.resourceId}`:''} · {item.actorId}</Text></View><Text style={[s.risk,{color:item.risk==='high'?colors.purple:item.risk==='medium'?colors.primary:colors.success}]}>{item.risk}</Text></View><Text style={s.time}>{new Date(item.createdAt).toLocaleString()}</Text><Text style={s.metadata}>{JSON.stringify(item.metadata)}</Text></View>)}{visible.length===0&&<Text style={s.empty}>No audit records match this filter yet.</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},filters:{flexDirection:'row',gap:7},filter:{paddingVertical:8,paddingHorizontal:12,borderRadius:10,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},active:{backgroundColor:colors.primary,borderColor:colors.primary},filterText:{color:colors.muted,fontSize:12,textTransform:'capitalize'},activeText:{color:colors.bg,fontWeight:'800'},meta:{color:colors.muted,fontSize:11},card:{padding:14,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:6},top:{flexDirection:'row',alignItems:'center'},copy:{flex:1},action:{color:colors.text,fontWeight:'800'},risk:{fontWeight:'900',fontSize:11,textTransform:'uppercase'},time:{color:colors.muted,fontSize:11},metadata:{color:colors.muted,fontSize:11,lineHeight:16},empty:{color:colors.muted,lineHeight:22}});
