import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { createSchedule, loadAutomationRuns, loadSchedules, runSchedule, toggleSchedule, ScheduleRecord, AutomationRun } from '../src/backend/automation';
import { colors, radii } from '../src/ui/theme';
import { useEffect, useState } from 'react';
export default function Automation(){const [schedules,setSchedules]=useState<ScheduleRecord[]>([]);const [runs,setRuns]=useState<AutomationRun[]>([]);const [name,setName]=useState('Daily workspace health');const refresh=async()=>{setSchedules(await loadSchedules());setRuns(await loadAutomationRuns())};useEffect(()=>{void refresh()},[]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Header title="Automation"/><Text style={s.subtitle}>Durable local schedules make Nova useful beyond a single session. Every run is persisted and auditable.</Text><View style={s.form}><TextInput value={name} onChangeText={setName} placeholder="Schedule name" placeholderTextColor={colors.muted} style={s.input}/><Pressable style={s.primary} onPress={async()=>{await createSchedule({workspaceId:'nova-local',name,toolId:'diagnostic-report',input:{source:'automation'},cadence:'daily'});await refresh();Alert.alert('Schedule created','The next daily run was persisted locally.')}}><Ionicons name="timer-outline" color={colors.bg} size={18}/><Text style={s.primaryText}>Create daily schedule</Text></Pressable></View><Text style={s.section}>Schedules ({schedules.length})</Text>{schedules.map(schedule=><View key={schedule.id} style={s.card}><View style={s.row}><View style={s.copy}><Text style={s.name}>{schedule.name}</Text><Text style={s.meta}>{schedule.toolId} · {schedule.cadence} · next {new Date(schedule.nextRunAt).toLocaleString()}</Text></View><Text style={[s.state,{color:schedule.enabled?colors.success:colors.muted}]}>{schedule.enabled?'on':'off'}</Text></View><View style={s.actions}><Pressable style={s.secondary} onPress={async()=>{await toggleSchedule(schedule.id);await refresh()}}><Text style={s.secondaryText}>{schedule.enabled?'Pause':'Enable'}</Text></Pressable><Pressable style={s.secondary} onPress={async()=>{await runSchedule(schedule);await refresh();Alert.alert('Run completed','The automation run and notification were persisted.')}}><Text style={s.secondaryText}>Run now</Text></Pressable></View></View>)}<Text style={s.section}>Recent runs ({runs.length})</Text>{runs.slice(0,10).map(run=><View key={run.id} style={s.run}><Ionicons name={run.status==='completed'?'checkmark-circle':'time-outline'} color={run.status==='completed'?colors.success:colors.primary} size={18}/><View style={s.copy}><Text style={s.name}>{run.id}</Text><Text style={s.meta}>{run.status} · {new Date(run.startedAt).toLocaleString()}</Text></View></View>)}</ScrollView></SafeAreaView>}
function Header({title}:{title:string}){return <View style={s.header}><View><Text style={s.eyebrow}>NOVA / AUTOMATION</Text><Text style={s.title}>{title}</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},form:{padding:14,borderRadius:radii.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:9},input:{backgroundColor:colors.surface2,borderColor:colors.border,borderWidth:1,borderRadius:10,color:colors.text,padding:12},primary:{backgroundColor:colors.primary,borderRadius:11,padding:13,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},primaryText:{color:colors.bg,fontWeight:'800'},section:{color:colors.muted,textTransform:'uppercase',fontSize:11,letterSpacing:1.4,fontWeight:'800',marginTop:8},card:{padding:14,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:10},row:{flexDirection:'row',alignItems:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800'},meta:{color:colors.muted,fontSize:11,marginTop:4},state:{fontWeight:'900',fontSize:11},actions:{flexDirection:'row',gap:8},secondary:{flex:1,padding:11,borderRadius:10,borderWidth:1,borderColor:colors.border,alignItems:'center'},secondaryText:{color:colors.primary,fontWeight:'800'},run:{padding:13,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:9}});
