import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { capturePhoto, pickMedia } from '../src/platform/capabilities';
import { useNova } from '../src/state/NovaProvider';
import { colors, radii } from '../src/ui/theme';

export default function CaptureScreen() { const { capabilities, requestPermission } = useNova(); const capture = async () => { const result = await capturePhoto(); if ('permission' in result && result.permission) Alert.alert('Camera permission needed', 'Nova will not access the camera until you approve it in system settings.'); else if (!result.canceled) Alert.alert('Captured', 'The photo is ready to be indexed in Files.'); }; return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Header title="Capture"/><Text style={s.subtitle}>Bring camera, media, and voice inputs into the local workspace with explicit permission gates.</Text><View style={s.hero}><View style={s.heroIcon}><Ionicons name="scan-outline" size={30} color={colors.primary}/></View><Text style={s.heroTitle}>Capture a moment</Text><Text style={s.heroCopy}>Expo Go and web gracefully show a fallback instead of failing when native hardware is unavailable.</Text><Pressable style={s.primary} onPress={capture}><Ionicons name="camera-outline" size={18} color={colors.bg}/><Text style={s.primaryText}>Open camera</Text></Pressable></View><Capability label="Camera" value={capabilities.camera} onPress={() => requestPermission('camera')}/><Capability label="Microphone" value={capabilities.microphone} onPress={() => requestPermission('microphone')}/><Capability label="Media library" value={capabilities.mediaLibrary} onPress={() => requestPermission('mediaLibrary')}/><Pressable style={s.row} onPress={async () => { const result = await pickMedia(); if (!result.canceled) Alert.alert('Media selected', 'Selected media can be imported from the Files workspace.'); }}><Ionicons name="images-outline" size={20} color={colors.primary}/><Text style={s.rowText}>Choose from media library</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable></ScrollView></SafeAreaView> }
function Header({ title }: { title:string }) { return <View style={s.header}><View><Text style={s.eyebrow}>NOVA / INPUTS</Text><Text style={s.title}>{title}</Text></View><Pressable style={s.close} onPress={() => router.back()}><Ionicons name="close" size={20} color={colors.text}/></Pressable></View> }
function Capability({ label, value, onPress }: { label:string; value:string; onPress:()=>void }) { return <View style={s.cap}><View><Text style={s.label}>{label}</Text><Text style={s.meta}>{value}</Text></View><Pressable onPress={onPress}><Text style={s.manage}>{value === 'granted' ? 'Granted' : 'Manage'}</Text></Pressable></View> }
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:32,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22,marginBottom:8},hero:{padding:18,borderRadius:radii.lg,backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,gap:10},heroIcon:{width:56,height:56,borderRadius:18,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},heroTitle:{color:colors.text,fontSize:20,fontWeight:'800'},heroCopy:{color:colors.muted,lineHeight:20},primary:{backgroundColor:colors.primary,borderRadius:12,padding:13,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8,marginTop:4},primaryText:{color:colors.bg,fontWeight:'800'},cap:{padding:15,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},label:{color:colors.text,fontWeight:'800'},meta:{color:colors.muted,fontSize:12,marginTop:4,textTransform:'capitalize'},manage:{color:colors.primary,fontWeight:'800'},row:{padding:15,borderRadius:radii.md,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',gap:10},rowText:{color:colors.text,fontWeight:'700',flex:1}});
