import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNova } from '../src/state/NovaProvider';
import { colors, radii } from '../src/ui/theme';
export default function DiagnosticsScreen(){const {runs,jobs,events,files,capabilities,ready}=useNova();return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / OBSERVABILITY</Text><Text style={s.title}>Diagnostics</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" size={20} color={colors.text}/></Pressable></View><Text style={s.subtitle}>A local health view for troubleshooting offline execution without uploading private data.</Text><View style={s.grid}><Metric label="Runtime" value={ready?'Ready':'Loading'}/><Metric label="Runs" value={`${runs.length}`}/><Metric label="Jobs" value={`${jobs.length}`}/><Metric label="Events" value={`${events.length}`}/><Metric label="Files" value={`${files.length}`}/><Metric label="Native gates" value={`${Object.values(capabilities).filter((value)=>value==='granted').length}/4`}/></View><Text style={s.section}>Recent event log</Text>{events.slice(0,8).map((event)=><View key={event.id} style={s.event}><View style={s.dot}/><View style={s.copy}><Text style={s.eventType}>{event.type}</Text><Text style={s.eventText}>{event.message}</Text></View><Text style={s.time}>{new Date(event.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text></View>)}{events.length===0&&<Text style={s.empty}>No events yet. Start a local run or import a file to populate the persisted log.</Text>}</ScrollView></SafeAreaView>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:32,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{width:'31%',minWidth:95,padding:12,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},metricValue:{color:colors.primary,fontWeight:'900',fontSize:20},metricLabel:{color:colors.muted,fontSize:11,marginTop:4},section:{color:colors.muted,textTransform:'uppercase',fontSize:11,letterSpacing:1.4,fontWeight:'800',marginTop:8},event:{padding:13,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'flex-start',gap:10},dot:{width:8,height:8,borderRadius:4,backgroundColor:colors.primary,marginTop:5},copy:{flex:1},eventType:{color:colors.text,fontWeight:'800',fontSize:12},eventText:{color:colors.muted,fontSize:12,marginTop:3},time:{color:colors.muted,fontSize:10},empty:{color:colors.muted,lineHeight:22,paddingTop:8}});
