import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNova } from '../src/state/NovaProvider';
import { colors, radii } from '../src/ui/theme';

export default function FilesScreen() { const { files, importFiles, createNote, deleteFile, exportFiles } = useNova(); return <SafeAreaView style={s.safe}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / WORKSPACE</Text><Text style={s.title}>Files</Text><Text style={s.subtitle}>{files.length} indexed local assets</Text></View><Pressable style={s.back} onPress={() => router.back()}><Ionicons name="close" size={20} color={colors.text}/></Pressable></View><View style={s.actions}><Action icon="cloud-upload-outline" title="Import" onPress={importFiles}/><Action icon="document-text-outline" title="New note" onPress={createNote}/><Action icon="share-outline" title="Export" onPress={exportFiles}/></View><FlatList data={files} keyExtractor={(item) => item.id} contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.empty}>Your Nova-owned workspace is empty. Import a document or create a note to start indexing.</Text>} renderItem={({ item }) => <Pressable style={s.row} onLongPress={() => Alert.alert('Delete file?', item.name, [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: () => deleteFile(item.id) }])}><View style={s.icon}><Ionicons name={item.kind === 'image' ? 'image-outline' : item.kind === 'audio' ? 'musical-notes-outline' : 'document-outline'} size={20} color={colors.primary}/></View><View style={s.copy}><Text style={s.name} numberOfLines={1}>{item.name}</Text><Text style={s.meta}>{item.kind} · {formatBytes(item.size)} · {new Date(item.updatedAt).toLocaleDateString()}</Text></View><Ionicons name="ellipsis-horizontal" color={colors.muted} size={18}/></Pressable>} /></SafeAreaView> }
function Action({ icon, title, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; onPress: () => void | Promise<void> }) { return <Pressable style={({ pressed }) => [s.action, pressed && { opacity: .7 }]} onPress={onPress}><Ionicons name={icon} size={19} color={colors.primary}/><Text style={s.actionText}>{title}</Text></Pressable> }
function formatBytes(size: number) { if (!size) return 'size unknown'; if (size < 1024) return `${size} B`; if (size < 1024 * 1024) return `${Math.round(size / 1024)} KB`; return `${(size / 1024 / 1024).toFixed(1)} MB`; }
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},header:{padding:20,flexDirection:'row',justifyContent:'space-between'},back:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:32,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:14,marginTop:4},actions:{paddingHorizontal:20,flexDirection:'row',gap:8},action:{flex:1,padding:12,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,alignItems:'center',gap:5},actionText:{color:colors.text,fontSize:12,fontWeight:'700'},list:{padding:20,gap:8},row:{backgroundColor:colors.surface,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,padding:12,flexDirection:'row',alignItems:'center',gap:12},icon:{width:40,height:40,borderRadius:12,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800',fontSize:14},meta:{color:colors.muted,fontSize:11,marginTop:4},empty:{color:colors.muted,lineHeight:22,paddingTop:28}});
