import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { loadDeadLetters, loadWorkerQueue } from '../src/backend/worker';
import { useDomain } from '../src/backend/DomainProvider';
import { colors, radii } from '../src/ui/theme';
import { useEffect, useState } from 'react';
export default function Jobs(){const {processJobs}=useDomain();const [queue,setQueue]=useState<Awaited<ReturnType<typeof loadWorkerQueue>>>([]);const [dead,setDead]=useState<Awaited<ReturnType<typeof loadDeadLetters>>>([]);const refresh=async()=>{setQueue(await loadWorkerQueue());setDead(await loadDeadLetters())};useEffect(()=>{void refresh()},[]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Header title="Worker Jobs"/><Text style={s.subtitle}>Priority-aware local jobs with retries and a dead-letter queue for failures that need attention.</Text><View style={s.actions}><Pressable style={s.primary} onPress={async()=>{await processJobs();await refresh();Alert.alert('Queue processed','Due jobs were executed and retry state was updated.')}}><Ionicons name="play-outline" color={colors.bg} size={17}/><Text style={s.primaryText}>Process due jobs</Text></Pressable><Pressable style={s.secondary} onPress={()=>void refresh()}><Ionicons name="refresh-outline" color={colors.primary} size={17}/><Text style={s.secondaryText}>Refresh</Text></Pressable></View><Text style={s.section}>Queue ({queue.length})</Text>{queue.map(job=><View key={job.id} style={s.job}><View style={s.icon}><Ionicons name="layers-outline" color={colors.primary} size={18}/></View><View style={s.copy}><Text style={s.name}>{job.toolId}</Text><Text style={s.meta}>{job.status} · attempt {job.attempts}/{job.maxAttempts}</Text></View><Text style={s.priority}>P{job.priority}</Text></View>)}{queue.length===0&&<Text style={s.empty}>The worker queue is clear.</Text>}<Text style={s.section}>Dead letters ({dead.length})</Text>{dead.map(job=><View key={job.id} style={s.dead}><Text style={s.name}>{job.toolId}</Text><Text style={s.meta}>{job.error ?? 'Failed after maximum retries.'}</Text></View>)}</ScrollView></SafeAreaView>}
function Header({title}:{title:string}){return <View style={s.header}><View><Text style={s.eyebrow}>NOVA / OPERATIONS</Text><Text style={s.title}>{title}</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},actions:{flexDirection:'row',gap:8},primary:{flex:1,backgroundColor:colors.primary,borderRadius:11,padding:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},primaryText:{color:colors.bg,fontWeight:'800',fontSize:12},secondary:{padding:13,borderRadius:11,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:7},secondaryText:{color:colors.primary,fontWeight:'800',fontSize:12},section:{color:colors.muted,textTransform:'uppercase',fontSize:11,letterSpacing:1.4,fontWeight:'800',marginTop:8},job:{padding:13,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:10},icon:{width:38,height:38,borderRadius:11,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800'},meta:{color:colors.muted,fontSize:11,marginTop:4},priority:{color:colors.primary,fontWeight:'900'},dead:{padding:13,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.purple},empty:{color:colors.muted,lineHeight:22}});
