import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useDomain } from '../src/backend/DomainProvider';
import { colors, radii } from '../src/ui/theme';
export default function ProjectsHub(){const {projects,tasks,createPlan}=useDomain();const [name,setName]=useState('');const [description,setDescription]=useState('');return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Header title="Projects & Plans"/><Text style={s.subtitle}>Create a project and let the local backend generate its first executable plan.</Text><View style={s.form}><TextInput value={name} onChangeText={setName} placeholder="Project name" placeholderTextColor={colors.muted} style={s.input}/><TextInput value={description} onChangeText={setDescription} placeholder="Outcome and context" placeholderTextColor={colors.muted} style={[s.input,s.multi]} multiline/><Pressable style={s.primary} onPress={async()=>{if(!name.trim())return Alert.alert('Name required','Give the project a name first.');await createPlan(name,description);setName('');setDescription('');Alert.alert('Plan created','The project and four starter tasks were saved locally.')}}><Ionicons name="add-circle-outline" color={colors.bg} size={18}/><Text style={s.primaryText}>Create project plan</Text></Pressable></View><Text style={s.section}>Projects ({projects.length})</Text>{projects.map(project=><View key={project.id} style={s.card}><View style={s.cardTop}><View style={[s.projectDot,{backgroundColor:project.color}]}/><Text style={s.cardTitle}>{project.name}</Text><Text style={s.badge}>{project.status}</Text></View><Text style={s.copy}>{project.description}</Text><Text style={s.meta}>{tasks.filter(task=>task.projectId===project.id).length} tasks · updated {new Date(project.updatedAt).toLocaleDateString()}</Text></View>)}{projects.length===0&&<Text style={s.empty}>No projects yet. Create the first project plan above.</Text>}</ScrollView></SafeAreaView>}
function Header({title}:{title:string}){return <View style={s.header}><View><Text style={s.eyebrow}>NOVA / DELIVERY</Text><Text style={s.title}>{title}</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View>}
import { useState } from 'react';
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},form:{backgroundColor:colors.surface,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,padding:15,gap:9},input:{backgroundColor:colors.surface2,borderColor:colors.border,borderWidth:1,borderRadius:10,color:colors.text,padding:12},multi:{minHeight:76,textAlignVertical:'top'},primary:{backgroundColor:colors.primary,borderRadius:11,padding:13,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},primaryText:{color:colors.bg,fontWeight:'800'},section:{color:colors.muted,textTransform:'uppercase',fontSize:11,letterSpacing:1.4,fontWeight:'800',marginTop:8},card:{backgroundColor:colors.surface,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,padding:15,gap:8},cardTop:{flexDirection:'row',alignItems:'center',gap:8},projectDot:{width:10,height:10,borderRadius:5},cardTitle:{color:colors.text,fontWeight:'800',fontSize:16,flex:1},badge:{color:colors.primary,fontSize:11,textTransform:'capitalize'},copy:{color:colors.muted,lineHeight:20},meta:{color:colors.muted,fontSize:11},empty:{color:colors.muted,lineHeight:22}});
