import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { executeFailover, heartbeatRegion, loadReplicationState, planFailover, ReplicationState } from '../src/backend/regions';
import { getRegionalWorkerStatus } from '../src/backend/worker';
import { colors, radii } from '../src/ui/theme';
import { useEffect, useState } from 'react';
export default function Regions(){const [state,setState]=useState<ReplicationState|null>(null);const [worker,setWorker]=useState<{primaryRegion:string;failoverCount:number;lastSequence:number;regions:Array<{id:string;lag:number;status:string}>}|null>(null);const refresh=async()=>{setState(await loadReplicationState());setWorker(await getRegionalWorkerStatus())};useEffect(()=>{void refresh()},[]);const failover=async()=>{if(!state)return;const plan=await planFailover('nova-local','Operator initiated regional failover');Alert.alert('Failover plan',`${plan.fromRegion} → ${plan.toRegion}\n${plan.dataLossWindow} unapplied entries\n${plan.requiresOperatorReview?'Operator review required.':'No replication gap detected.'}`,[{text:'Cancel',style:'cancel'},{text:'Promote',style:'destructive',onPress:async()=>{await executeFailover(plan);await refresh();Alert.alert('Region promoted',`${plan.toRegion} is now primary.`)}}])};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / HIGH AVAILABILITY</Text><Text style={s.title}>Multi-Region</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View><Text style={s.subtitle}>Replication is ordered by sequence, workers use leader leases, and failover is explicit so operators can review any replication gap before promotion.</Text><View style={s.summary}><Metric label="Primary" value={state?.primaryRegion??'—'}/><Metric label="Sequence" value={String(worker?.lastSequence??0)}/><Metric label="Failovers" value={String(worker?.failoverCount??0)}/></View><Pressable style={s.primary} onPress={failover}><Ionicons name="swap-horizontal-outline" color={colors.bg} size={18}/><Text style={s.primaryText}>Plan regional failover</Text></Pressable><Text style={s.section}>Regions</Text>{state?.regions.map(region=><View key={region.id} style={s.card}><View style={s.row}><View style={s.copy}><Text style={s.name}>{region.name}</Text><Text style={s.meta}>{region.id} · priority {region.priority} · {region.latencyMs}ms</Text></View><Text style={[s.status,{color:region.status==='unavailable'?colors.purple:region.status==='promoted'?colors.primary:colors.success}]}>{region.status}</Text></View><Text style={s.meta}>Applied sequence {region.lastAppliedSequence} · heartbeat {new Date(region.lastHeartbeatAt).toLocaleTimeString()}</Text><Pressable style={s.secondary} onPress={async()=>{await heartbeatRegion(region.id,Math.max(1,region.latencyMs),true);await refresh()}}><Text style={s.secondaryText}>Heartbeat</Text></Pressable></View>)}<Text style={s.section}>Worker posture</Text><View style={s.card}><Text style={s.name}>Leader-lease execution</Text><Text style={s.meta}>Only the primary region processes the queue. Standbys replicate pending entries and can be promoted after operator review.</Text></View></ScrollView></SafeAreaView>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},summary:{flexDirection:'row',gap:8},metric:{flex:1,padding:13,backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radii.md},metricValue:{color:colors.text,fontWeight:'900',fontSize:16},primary:{backgroundColor:colors.primary,borderRadius:11,padding:13,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},primaryText:{color:colors.bg,fontWeight:'800'},section:{color:colors.muted,textTransform:'uppercase',fontSize:11,letterSpacing:1.4,fontWeight:'800',marginTop:8},card:{padding:14,borderRadius:radii.md,backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,gap:8},row:{flexDirection:'row',alignItems:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800'},meta:{color:colors.muted,fontSize:11,lineHeight:17},status:{fontWeight:'900',textTransform:'uppercase',fontSize:11},secondary:{padding:10,borderRadius:10,borderColor:colors.border,borderWidth:1,alignItems:'center'},secondaryText:{color:colors.primary,fontWeight:'800'}});
