import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useDomain } from '../src/backend/DomainProvider';
import { buildSearchIndex, searchIndex } from '../src/backend/search';
import { useNova } from '../src/state/NovaProvider';
import { colors, radii } from '../src/ui/theme';
import { useMemo, useState } from 'react';
export default function SearchScreen(){const {projects,tasks}=useDomain();const {files,memories,runs}=useNova();const [query,setQuery]=useState('');const index=useMemo(()=>buildSearchIndex({files,memories,projects,tasks,runs},'nova-local'),[files,memories,projects,tasks,runs]);const results=searchIndex(index,query);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / INDEX</Text><Text style={s.title}>Global Search</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View><TextInput value={query} onChangeText={setQuery} placeholder="Search projects, tasks, memories, files, runs" placeholderTextColor={colors.muted} autoFocus style={s.input}/><Text style={s.meta}>{query.trim()?`${results.length} ranked results`:`${index.length} indexed records`}</Text>{results.map(document=><View key={`${document.entityType}-${document.id}`} style={s.result}><View style={s.icon}><Ionicons name={document.entityType==='task'?'checkbox-outline':document.entityType==='project'?'briefcase-outline':document.entityType==='file'?'document-outline':document.entityType==='memory'?'bookmark-outline':'pulse-outline'} color={colors.primary} size={18}/></View><View style={s.copy}><Text style={s.name}>{document.title}</Text><Text style={s.body} numberOfLines={2}>{document.body}</Text><Text style={s.type}>{document.entityType} · {new Date(document.updatedAt).toLocaleDateString()}</Text></View></View>)}{query.trim()&&results.length===0&&<Text style={s.empty}>No matches. Try a project name, task label, or memory keyword.</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,color:colors.text,padding:14,fontSize:15},meta:{color:colors.muted,fontSize:12},result:{padding:14,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',gap:10},icon:{width:38,height:38,borderRadius:11,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800'},body:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:4},type:{color:colors.primary,fontSize:10,marginTop:5,textTransform:'capitalize'},empty:{color:colors.muted,lineHeight:22}});
