import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNova } from '../src/state/NovaProvider';
import { colors, radii } from '../src/ui/theme';
export default function StorageScreen(){const {files,settings,updateSettings,recoverStorage}=useNova();return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / DATA</Text><Text style={s.title}>Storage</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" size={20} color={colors.text}/></Pressable></View><Text style={s.subtitle}>Nova owns a durable workspace inside app storage. The index is backed up before each write.</Text><View style={s.metric}><Text style={s.metricValue}>{files.length}</Text><Text style={s.metricLabel}>indexed files</Text><Text style={s.metricHint}>Safe CRUD · metadata-first · recoverable</Text></View><Setting title="Auto-index imports" detail="Update the local metadata index as files arrive." control={<Switch value={settings.autoIndex} onValueChange={(value)=>updateSettings({...settings,autoIndex:value})} trackColor={{true:colors.primary,false:colors.border}} thumbColor={colors.text}/>} /><Setting title="Keep cache copies" detail="Retain temporary import copies for offline re-opening." control={<Switch value={settings.keepCache} onValueChange={(value)=>updateSettings({...settings,keepCache:value})} trackColor={{true:colors.primary,false:colors.border}} thumbColor={colors.text}/>} /><Setting title="Max file size" detail={`${settings.maxFileSizeMb} MB per import`} control={<Text style={s.value}>{settings.maxFileSizeMb} MB</Text>} /><Pressable style={s.recover} onPress={()=>{void recoverStorage();Alert.alert('Storage recovered','Nova restored the last known-good workspace index.')}}><Ionicons name="refresh-outline" size={19} color={colors.primary}/><Text style={s.recoverText}>Recover last known-good index</Text></Pressable><Text style={s.section}>Permissions</Text><Text style={s.copy}>Open the Permissions center to inspect camera, microphone, media, and notification access.</Text><Pressable style={s.link} onPress={()=>router.push('/permissions')}><Text style={s.linkText}>Open Permissions</Text><Ionicons name="chevron-forward" color={colors.primary} size={18}/></Pressable></ScrollView></SafeAreaView>}
function Setting({title,detail,control}:{title:string;detail:string;control:React.ReactNode}){return <View style={s.setting}><View style={s.copyWrap}><Text style={s.label}>{title}</Text><Text style={s.copy}>{detail}</Text></View>{control}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:32,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},metric:{padding:18,borderRadius:radii.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},metricValue:{color:colors.primary,fontSize:36,fontWeight:'900'},metricLabel:{color:colors.text,fontWeight:'800'},metricHint:{color:colors.muted,fontSize:12,marginTop:5},setting:{padding:15,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},copyWrap:{flex:1,paddingRight:12},label:{color:colors.text,fontWeight:'800'},copy:{color:colors.muted,fontSize:12,lineHeight:19,marginTop:4},value:{color:colors.primary,fontWeight:'800'},recover:{padding:15,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:10},recoverText:{color:colors.text,fontWeight:'800'},section:{color:colors.muted,textTransform:'uppercase',fontSize:11,letterSpacing:1.4,fontWeight:'800',marginTop:8},link:{padding:15,borderRadius:radii.md,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},linkText:{color:colors.primary,fontWeight:'800'}});
