import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { agentTools } from '../src/agent/runtime';
import { advancedTools } from '../src/agent/advancedTools';
import { operationsTools } from '../src/agent/operationsTools';
import { productionTools } from '../src/agent/productionTools';
import { useNova } from '../src/state/NovaProvider';
import { colors, radii } from '../src/ui/theme';

const groups = [
  { id: 'core', title: 'Core agent tools', detail: 'Planning, extraction, indexing, and exports.', tools: agentTools },
  { id: 'advanced', title: 'Advanced local tools', detail: 'Redaction, transforms, diagnostics, and webhooks.', tools: advancedTools },
  { id: 'operations', title: 'Operations tools', detail: 'Queues, workers, audit, and resilience workflows.', tools: operationsTools },
  { id: 'production', title: 'Production readiness', detail: 'Credentials, telemetry, secure storage, and backend checks.', tools: productionTools },
] as const;

export default function ToolsCenter(){const {startRun}=useNova();const tools=groups.flatMap((group)=>group.tools);const safeCount=tools.filter((tool)=>tool.risk==='safe').length;const gatedCount=tools.length-safeCount;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / AGENT RUNTIME</Text><Text style={s.title}>Tools</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" size={20} color={colors.text}/></Pressable></View><Text style={s.subtitle}>Every tool declares an input type and risk level. Production tools use bounded network requests, secure credential checks, and persisted recovery paths. Review-gated tools pause in Approvals before execution.</Text><View style={s.summary}><Metric label="Tools" value={String(tools.length)}/><Metric label="Safe" value={String(safeCount)}/><Metric label="Gated" value={String(gatedCount)}/></View><View style={s.banner}><Ionicons name="cube-outline" size={20} color={colors.primary}/><View style={s.copy}><Text style={s.bannerTitle}>Sandbox-ready backend tools</Text><Text style={s.bannerText}>Deterministic redact, summarize, word-count, uppercase, and risk-score commands reject URLs and shell-like input before execution.</Text></View></View>{groups.map(group=><View key={group.id} style={s.group}><View style={s.groupHeader}><View><Text style={s.section}>{group.title}</Text><Text style={s.groupDetail}>{group.detail}</Text></View><Text style={s.count}>{group.tools.length}</Text></View>{group.tools.map(tool=><Pressable key={tool.id} style={s.tool} onPress={()=>{startRun(`Run ${tool.name}`,tool.id);Alert.alert(tool.risk==='safe'?'Queued':'Approval gate',tool.risk==='safe'?'The retryable local job was queued.':'This tool created an approval request before execution.')}}><View style={s.icon}><Ionicons name={tool.risk==='safe'?'sparkles-outline':'shield-checkmark-outline'} size={21} color={tool.risk==='safe'?colors.primary:colors.purple}/></View><View style={s.copy}><Text style={s.name}>{tool.name}</Text><Text style={s.desc}>{tool.description}</Text><Text style={s.meta}>{tool.input} input · {tool.risk} risk · {tool.id}</Text></View><Ionicons name="play-circle-outline" color={colors.primary} size={22}/></Pressable>)}</View>)}<Pressable style={s.diag} onPress={()=>router.push('/diagnostics')}><Text style={s.diagText}>Open runtime diagnostics</Text><Ionicons name="chevron-forward" color={colors.primary} size={18}/></Pressable></ScrollView></SafeAreaView>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:32,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22,marginBottom:4},summary:{flexDirection:'row',gap:10},metric:{flex:1,backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radii.md,padding:12},metricValue:{color:colors.text,fontSize:22,fontWeight:'900'},metricLabel:{color:colors.muted,fontSize:11,textTransform:'uppercase',letterSpacing:1},banner:{backgroundColor:colors.surface,borderColor:colors.primary,borderWidth:1,borderRadius:radii.md,padding:13,flexDirection:'row',gap:12},bannerTitle:{color:colors.text,fontWeight:'900'},bannerText:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:3},group:{gap:9,marginTop:4},groupHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},section:{color:colors.text,fontSize:16,fontWeight:'900'},groupDetail:{color:colors.muted,fontSize:12,marginTop:2},count:{color:colors.primary,fontWeight:'900'},tool:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radii.md,padding:13,flexDirection:'row',alignItems:'center',gap:12},icon:{width:42,height:42,borderRadius:12,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800',fontSize:15},desc:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:3},meta:{color:colors.primary,fontSize:11,marginTop:6,textTransform:'capitalize'},diag:{marginTop:4,padding:15,borderRadius:radii.md,backgroundColor:colors.surface,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},diagText:{color:colors.primary,fontWeight:'800'}});
