import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { agentTools } from '../src/agent/runtime';
import { advancedTools } from '../src/agent/advancedTools';
import { operationsTools } from '../src/agent/operationsTools';
import { useNova } from '../src/state/NovaProvider';
import { colors, radii } from '../src/ui/theme';
export default function ToolsCenter(){const {startRun}=useNova();const tools=[...agentTools,...advancedTools,...operationsTools];return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>NOVA / AGENT RUNTIME</Text><Text style={s.title}>Tools</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" size={20} color={colors.text}/></Pressable></View><Text style={s.subtitle}>Every tool declares an input type and risk level. Review-gated tools pause in Approvals before execution.</Text>{tools.map(tool=><Pressable key={tool.id} style={s.tool} onPress={()=>{startRun(`Run ${tool.name}`,tool.id);Alert.alert(tool.risk==='safe'?'Queued':'Approval gate',tool.risk==='safe'?'The retryable local job was queued.':'This tool created an approval request before execution.')}}><View style={s.icon}><Ionicons name={tool.risk==='safe'?'sparkles-outline':'shield-checkmark-outline'} size={21} color={tool.risk==='safe'?colors.primary:colors.purple}/></View><View style={s.copy}><Text style={s.name}>{tool.name}</Text><Text style={s.desc}>{tool.description}</Text><Text style={s.meta}>{tool.input} input · {tool.risk} risk · {tool.id}</Text></View><Ionicons name="play-circle-outline" color={colors.primary} size={22}/></Pressable>)}<Pressable style={s.diag} onPress={()=>router.push('/diagnostics')}><Text style={s.diagText}>Open runtime diagnostics</Text><Ionicons name="chevron-forward" color={colors.primary} size={18}/></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:10},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:32,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22,marginBottom:10},tool:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radii.md,padding:13,flexDirection:'row',alignItems:'center',gap:12},icon:{width:42,height:42,borderRadius:12,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800',fontSize:15},desc:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:3},meta:{color:colors.primary,fontSize:11,marginTop:6,textTransform:'capitalize'},diag:{marginTop:4,padding:15,borderRadius:radii.md,backgroundColor:colors.surface,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},diagText:{color:colors.primary,fontWeight:'800'}});
