import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useDomain } from '../src/backend/DomainProvider';
import { colors, radii } from '../src/ui/theme';
export default function Workflows(){const {workflows,addDefaultWorkflow,runWorkflow,toggleWorkflow}=useDomain();return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Header title="Workflows"/><Text style={s.subtitle}>Compose durable local automations around imports, approvals, tools, notifications, and exports.</Text><Pressable style={s.primary} onPress={async()=>{await addDefaultWorkflow();Alert.alert('Workflow created','File to task pipeline is ready.')}}><Ionicons name="git-branch-outline" color={colors.bg} size={18}/><Text style={s.primaryText}>Add file-to-task workflow</Text></Pressable>{workflows.map(workflow=><View key={workflow.id} style={s.card}><View style={s.top}><View style={s.copy}><Text style={s.name}>{workflow.name}</Text><Text style={s.meta}>{workflow.trigger} trigger · {workflow.steps.length} steps</Text></View><Text style={[s.state,{color:workflow.enabled?colors.success:colors.muted}]}>{workflow.enabled?'enabled':'paused'}</Text></View><Text style={s.description}>{workflow.description}</Text><View style={s.steps}>{workflow.steps.map(step=><View key={step.id} style={s.step}><Ionicons name={step.risk==='safe'?'checkmark-circle-outline':'shield-checkmark-outline'} size={16} color={step.risk==='safe'?colors.primary:colors.purple}/><Text style={s.stepText}>{step.name}</Text><Text style={s.risk}>{step.risk}</Text></View>)}</View><View style={s.actions}><Pressable style={s.secondary} onPress={()=>void toggleWorkflow(workflow.id)}><Text style={s.secondaryText}>{workflow.enabled?'Pause':'Enable'}</Text></Pressable><Pressable style={s.secondary} onPress={async()=>{await runWorkflow(workflow.id);Alert.alert('Workflow completed','All configured steps were processed locally.')}}><Text style={s.secondaryText}>Run now</Text></Pressable></View></View>)}{workflows.length===0&&<Text style={s.empty}>No workflows yet. Add the default file-to-task pipeline.</Text>}</ScrollView></SafeAreaView>}
function Header({title}:{title:string}){return <View style={s.header}><View><Text style={s.eyebrow}>NOVA / AUTOMATION</Text><Text style={s.title}>{title}</Text></View><Pressable style={s.close} onPress={()=>router.back()}><Ionicons name="close" color={colors.text} size={20}/></Pressable></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:20,gap:12},header:{flexDirection:'row',justifyContent:'space-between'},close:{width:38,height:38,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.primary,fontWeight:'700'},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:4},subtitle:{color:colors.muted,fontSize:15,lineHeight:22},primary:{backgroundColor:colors.primary,borderRadius:11,padding:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},primaryText:{color:colors.bg,fontWeight:'800'},card:{padding:15,borderRadius:radii.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:10},top:{flexDirection:'row',alignItems:'center'},copy:{flex:1},name:{color:colors.text,fontWeight:'800',fontSize:16},meta:{color:colors.muted,fontSize:11,marginTop:4},state:{fontWeight:'800',fontSize:11},description:{color:colors.muted,lineHeight:20},steps:{gap:7},step:{flexDirection:'row',alignItems:'center',gap:7},stepText:{color:colors.text,fontSize:12,flex:1},risk:{color:colors.muted,fontSize:10,textTransform:'capitalize'},actions:{flexDirection:'row',gap:8},secondary:{flex:1,padding:11,borderRadius:10,borderWidth:1,borderColor:colors.border,alignItems:'center'},secondaryText:{color:colors.primary,fontWeight:'800'},empty:{color:colors.muted,lineHeight:22}});
