import { Ionicons } from '@expo/vector-icons'; import { useMemo } from 'react'; import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'; import { SafeAreaView } from 'react-native-safe-area-context'; import { useNova } from '../../src/state/NovaProvider'; import { colors, radii } from '../../src/ui/theme';
const icons: any = { brain: 'bulb-outline', 'git-branch': 'git-branch-outline', 'book-open': 'book-outline', calculator: 'calculator-outline', scan: 'scan-outline', list: 'list-outline', sparkles: 'sparkles-outline', globe: 'globe-outline', 'code-slash': 'code-slash-outline', analytics: 'analytics-outline', language: 'language-outline', pricetag: 'pricetag-outline', map: 'map-outline', construct: 'construct-outline', pulse: 'pulse-outline', 'shield-checkmark': 'shield-checkmark-outline' };
const categoryOrder = ['Cognition', 'Utilities', 'Productivity', 'Agentic', 'Advanced', 'Operations', 'Production'];
const rank = (category: string) => { const index = categoryOrder.indexOf(category); return index === -1 ? 999 : index; };
export default function Tools() {
  const { tools } = useNova();
  const sections = useMemo(() => {
    const grouped = new Map<string, typeof tools>();
    tools.forEach((tool) => { const bucket = grouped.get(tool.category) ?? []; bucket.push(tool); grouped.set(tool.category, bucket); });
    return [...grouped.entries()].sort((a, b) => rank(a[0]) - rank(b[0]));
  }, [tools]);
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>NOVA / TOOLBOX</Text><Text style={s.title}>Tools</Text><Text style={s.subtitle}>{tools.length} focused capabilities. Utility tools run fully on-device — the rest stream from your connected backend.</Text>{sections.map(([category, categoryTools]) => <View key={category} style={s.section}><Text style={s.sectionTitle}>{category}</Text>{categoryTools.map((tool) => <Pressable key={tool.id} style={s.tool}><View style={s.icon}><Ionicons name={icons[tool.icon] ?? 'sparkles-outline'} size={22} color={colors.primary} /></View><View style={s.copy}><Text style={s.name}>{tool.name}</Text><Text style={s.desc}>{tool.description}</Text></View><Ionicons name="chevron-forward" color={colors.muted} size={18} /></Pressable>)}</View>)}</ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg }, content: { padding: 20, gap: 10 }, eyebrow: { fontSize: 10, letterSpacing: 1.5, color: colors.primary, fontWeight: '700' }, title: { color: colors.text, fontSize: 32, fontWeight: '800', marginTop: 4 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginBottom: 18 }, section: { gap: 8, marginBottom: 14 }, sectionTitle: { color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 3 }, tool: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radii.md, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, icon: { width: 42, height: 42, borderRadius: 12, backgroundColor: colors.surface2, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, name: { color: colors.text, fontWeight: '800', fontSize: 15 }, desc: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 } });
