// Theme engine for the Nova web frontend, recreating the nova-chat-khaki
// ("Nova — Quiet intelligence") design system. Default preset is Warm Paper —
// a warm, editorial, paper-like light theme with terracotta accent and serif
// display typography. All 12 presets from the original are reproduced.

export type ThemePreset = {
  id: string
  label: string
  background: string
  foreground: string
  paper: string
  paperDeep: string
  inkSoft: string
  inkFaint: string
  line: string
  lineStrong: string
  accent: string
  accentDark: string
  accentWash: string
  accentGreen: string
  accentBlue: string
  accentPurple: string
  accentGold: string
  dark?: boolean
}

export const THEMES: ThemePreset[] = [
  {
    id: 'warm-paper',
    label: 'Warm Paper',
    background: '#f6f3ee',
    foreground: '#2c2b29',
    paper: '#fbfaf8',
    paperDeep: '#efebe4',
    inkSoft: '#6d6a64',
    inkFaint: '#9b978f',
    line: '#e6e1d9',
    lineStrong: '#d8d1c6',
    accent: '#d85a3a',
    accentDark: '#b8462c',
    accentWash: '#f6dfd7',
    accentGreen: '#3a8a5c',
    accentBlue: '#3a6ad8',
    accentPurple: '#7c3ad8',
    accentGold: '#d89a3a',
  },
  {
    id: 'amethyst-night',
    label: 'Amethyst Night',
    background: '#17131f',
    foreground: '#ece7f5',
    paper: '#1e1829',
    paperDeep: '#120e1a',
    inkSoft: '#a89fc0',
    inkFaint: '#6f6588',
    line: '#2c2438',
    lineStrong: '#3c3252',
    accent: '#b08bd8',
    accentDark: '#9668c4',
    accentWash: '#2c2140',
    accentGreen: '#5cbd8a',
    accentBlue: '#6d8ce8',
    accentPurple: '#b08bd8',
    accentGold: '#d8b25c',
    dark: true,
  },
  {
    id: 'arctic-aurora',
    label: 'Arctic Aurora',
    background: '#eef3f5',
    foreground: '#233038',
    paper: '#f8fbfc',
    paperDeep: '#e2eaee',
    inkSoft: '#5d707a',
    inkFaint: '#93a4ad',
    line: '#d8e2e7',
    lineStrong: '#c3d2d9',
    accent: '#2f8f83',
    accentDark: '#22736a',
    accentWash: '#d5ece8',
    accentGreen: '#2f8f83',
    accentBlue: '#3a7ad8',
    accentPurple: '#6a5bd8',
    accentGold: '#caa03a',
  },
  {
    id: 'sunset-studio',
    label: 'Sunset Studio',
    background: '#faf0e9',
    foreground: '#3a2a24',
    paper: '#fff8f4',
    paperDeep: '#f3e3d8',
    inkSoft: '#8a6c60',
    inkFaint: '#b59a8e',
    line: '#efdcd0',
    lineStrong: '#e2c6b4',
    accent: '#e0603a',
    accentDark: '#c04a28',
    accentWash: '#fadfd2',
    accentGreen: '#5c9a4a',
    accentBlue: '#4a7ad0',
    accentPurple: '#9a5ad0',
    accentGold: '#d8a03a',
  },
  {
    id: 'zen-garden',
    label: 'Zen Garden',
    background: '#f0f2ec',
    foreground: '#2a2f28',
    paper: '#f8f9f5',
    paperDeep: '#e4e8dd',
    inkSoft: '#67705f',
    inkFaint: '#98a08e',
    line: '#dde2d2',
    lineStrong: '#c9d1ba',
    accent: '#5a7a4a',
    accentDark: '#476238',
    accentWash: '#dfe8d5',
    accentGreen: '#5a7a4a',
    accentBlue: '#4a7a9a',
    accentPurple: '#7a6aa8',
    accentGold: '#b8923a',
  },
  {
    id: 'sandstorm',
    label: 'Sandstorm',
    background: '#f2ead9',
    foreground: '#3d3226',
    paper: '#faf4e8',
    paperDeep: '#e8dcc4',
    inkSoft: '#857253',
    inkFaint: '#b3a184',
    line: '#e5d8bc',
    lineStrong: '#d5c3a0',
    accent: '#c07b2a',
    accentDark: '#a06320',
    accentWash: '#f2e0c4',
    accentGreen: '#6a8a3a',
    accentBlue: '#4a7ab0',
    accentPurple: '#8a6ab0',
    accentGold: '#c07b2a',
  },
  {
    id: 'candy-bloom',
    label: 'Candy Bloom',
    background: '#fceef2',
    foreground: '#3d2430',
    paper: '#fff7fa',
    paperDeep: '#f6e0e8',
    inkSoft: '#94687c',
    inkFaint: '#c09aab',
    line: '#f2d6e0',
    lineStrong: '#e4bccd',
    accent: '#e04a80',
    accentDark: '#c23468',
    accentWash: '#fad9e4',
    accentGreen: '#4aa06a',
    accentBlue: '#5a7ae0',
    accentPurple: '#a05ad0',
    accentGold: '#d8a04a',
  },
  {
    id: 'sapphire-circuit',
    label: 'Sapphire Circuit',
    background: '#0e1420',
    foreground: '#dfe8f5',
    paper: '#141c2c',
    paperDeep: '#0a0f1a',
    inkSoft: '#8a9ab5',
    inkFaint: '#5a6a85',
    line: '#223050',
    lineStrong: '#30406480',
    accent: '#4a8aff',
    accentDark: '#3a6fd8',
    accentWash: '#1a2a48',
    accentGreen: '#3ac88a',
    accentBlue: '#4a8aff',
    accentPurple: '#8a6af0',
    accentGold: '#d8b25c',
    dark: true,
  },
  {
    id: 'terminal-matrix',
    label: 'Terminal Matrix',
    background: '#0a0f0a',
    foreground: '#c8e8c8',
    paper: '#101810',
    paperDeep: '#060a06',
    inkSoft: '#6a8a6a',
    inkFaint: '#486048',
    line: '#1a2a1a',
    lineStrong: '#2a402a',
    accent: '#3ad85a',
    accentDark: '#2ab846',
    accentWash: '#123018',
    accentGreen: '#3ad85a',
    accentBlue: '#3ab8c8',
    accentPurple: '#6ac86a',
    accentGold: '#b8c83a',
    dark: true,
  },
  {
    id: 'vaporwave-grid',
    label: 'Vaporwave Grid',
    background: '#180f28',
    foreground: '#f0e8ff',
    paper: '#201438',
    paperDeep: '#100a20',
    inkSoft: '#a08cc8',
    inkFaint: '#6f5a95',
    line: '#2e1f4a',
    lineStrong: '#402f66',
    accent: '#ff6ac8',
    accentDark: '#e04ab0',
    accentWash: '#3a1f50',
    accentGreen: '#3ae8c8',
    accentBlue: '#6a8aff',
    accentPurple: '#b06aff',
    accentGold: '#ffd86a',
    dark: true,
  },
  {
    id: 'blueprint-grid',
    label: 'Blueprint Grid',
    background: '#16283f',
    foreground: '#e0ecf8',
    paper: '#1d3450',
    paperDeep: '#10203a',
    inkSoft: '#8fa8c8',
    inkFaint: '#5f7a9a',
    line: '#2a4468',
    lineStrong: '#3a5a85',
    accent: '#5ab8ff',
    accentDark: '#3a98e0',
    accentWash: '#1d3a58',
    accentGreen: '#4ac8a0',
    accentBlue: '#5ab8ff',
    accentPurple: '#9a8af0',
    accentGold: '#e0b85a',
    dark: true,
  },
  {
    id: 'aurora-3d',
    label: 'Aurora 3D',
    background: '#101826',
    foreground: '#e5f0f8',
    paper: '#182234',
    paperDeep: '#0b1220',
    inkSoft: '#8aa2b8',
    inkFaint: '#5c7186',
    line: '#263650',
    lineStrong: '#36486a',
    accent: '#4ac8c0',
    accentDark: '#34a8a0',
    accentWash: '#16323e',
    accentGreen: '#4ac88a',
    accentBlue: '#5a9ae8',
    accentPurple: '#8a7ae8',
    accentGold: '#d8b25c',
    dark: true,
  },
]

export const DEFAULT_THEME = 'warm-paper'

export function getTheme(id: string): ThemePreset {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]
}

export function applyTheme(id: string) {
  const t = getTheme(id)
  const root = document.documentElement
  root.setAttribute('data-nova-theme', t.id)
  const vars: Record<string, string> = {
    '--background': t.background,
    '--foreground': t.foreground,
    '--paper': t.paper,
    '--paper-deep': t.paperDeep,
    '--ink-soft': t.inkSoft,
    '--ink-faint': t.inkFaint,
    '--line': t.line,
    '--line-strong': t.lineStrong,
    '--accent': t.accent,
    '--accent-dark': t.accentDark,
    '--accent-wash': t.accentWash,
    '--accent-green': t.accentGreen,
    '--accent-blue': t.accentBlue,
    '--accent-purple': t.accentPurple,
    '--accent-gold': t.accentGold,
    '--radius': '.65rem',
  }
  for (const [k, v] of Object.entries(vars)) root.style.setProperty(k, v)
}
